// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from '@hey-api/client-fetch';
import type {
  GetApiAdminDashboardData,
  GetApiAdminDashboardResponse,
  GetApiAdminTransactionsData,
  GetApiAdminTransactionsResponse,
  GetApiAdminDocumentsData,
  GetApiAdminDocumentsResponse,
  GetApiAdminDocumentsByIdData,
  GetApiAdminDocumentsByIdResponse,
  GetApiAdminDocumentsByIdError,
  PatchApiAdminDocumentsByIdData,
  PatchApiAdminDocumentsByIdResponse,
  PatchApiAdminDocumentsByIdError,
  PostApiAdminDocumentsBulkData,
  PostApiAdminDocumentsBulkResponse,
  PostApiAdminDocumentsBulkError,
  GetApiAdminDocumentsByIdReportsData,
  GetApiAdminDocumentsByIdReportsResponse,
  PostApiAdminDocumentsByIdReportsData,
  PostApiAdminDocumentsByIdReportsResponse,
  PostApiAdminDocumentsByIdReportsError,
  PostApiAdminDocumentsByIdReportsByReportIdResolveData,
  PostApiAdminDocumentsByIdReportsByReportIdResolveResponse,
  PostApiAdminDocumentsByIdReportsByReportIdResolveError,
  PostApiAdminDocumentsByIdReportsResolveAllData,
  PostApiAdminDocumentsByIdReportsResolveAllResponse,
  GetApiAdminDocumentsPendingData,
  GetApiAdminDocumentsPendingResponse,
  PostApiAdminDocumentsPendingSearchData,
  PostApiAdminDocumentsPendingSearchResponse,
  PostApiAdminDocumentsPendingSearchError,
  PostApiAdminDocumentsByIdApproveData,
  PostApiAdminDocumentsByIdApproveResponse,
  PostApiAdminDocumentsByIdApproveError,
  PostApiAdminDocumentsByIdRejectData,
  PostApiAdminDocumentsByIdRejectResponse,
  PostApiAdminDocumentsByIdRejectError,
  GetApiAdminSellersData,
  GetApiAdminSellersResponse,
  GetApiAdminSettingsData,
  GetApiAdminSettingsResponse,
  PutApiAdminSettingsData,
  PutApiAdminSettingsResponse,
  PutApiAdminSettingsError,
  GetApiAdminStorageUsageData,
  GetApiAdminStorageUsageResponse,
  PostApiAuthRegisterData,
  PostApiAuthRegisterResponse,
  PostApiAuthRegisterError,
  PostApiAuthLoginData,
  PostApiAuthLoginResponse,
  PostApiAuthLoginError,
  PostApiAuthRefreshData,
  PostApiAuthRefreshResponse,
  PostApiAuthRefreshError,
  PostApiAuthLogoutData,
  PostApiAuthLogoutResponse,
  PostApiAuthVerifyEmailData,
  PostApiAuthVerifyEmailResponse,
  PostApiAuthVerifyEmailError,
  PostApiAuthResendVerificationData,
  PostApiAuthResendVerificationResponse,
  PostApiAuthExternalByProviderData,
  PostApiAuthExternalByProviderResponse,
  PostApiAuthExternalByProviderError,
  GetApiAuthOauthClientsData,
  GetApiAuthOauthClientsResponse,
  DeleteApiCartData,
  DeleteApiCartResponse,
  GetApiCartData,
  GetApiCartResponse,
  PostApiCartItemsData,
  PostApiCartItemsResponse,
  PostApiCartItemsError,
  DeleteApiCartItemsByDocumentIdData,
  DeleteApiCartItemsByDocumentIdResponse,
  GetApiAdminCategoriesData,
  GetApiAdminCategoriesResponse,
  PostApiAdminCategoriesData,
  PostApiAdminCategoriesResponse,
  PostApiAdminCategoriesError,
  DeleteApiAdminCategoriesByIdData,
  DeleteApiAdminCategoriesByIdResponse,
  DeleteApiAdminCategoriesByIdError,
  GetApiAdminCategoriesByIdData,
  GetApiAdminCategoriesByIdResponse,
  GetApiAdminCategoriesByIdError,
  PutApiAdminCategoriesByIdData,
  PutApiAdminCategoriesByIdResponse,
  PutApiAdminCategoriesByIdError,
  PostApiDocumentUploadData,
  PostApiDocumentUploadResponse,
  PostApiDocumentUploadError,
  PostApiFilesUploadData,
  PostApiFilesUploadResponse,
  PostApiFilesUploadBase64Data,
  PostApiFilesUploadBase64Response,
  GetApiFilesDownloadByKeyData,
  GetApiFilesPresignedByKeyData,
  GetApiLibraryData,
  GetApiLibraryResponse,
  PostApiLibraryByDocumentIdDownloadData,
  PostApiLibraryByDocumentIdDownloadResponse,
  PostApiLibraryByDocumentIdDownloadError,
  PostApiLibraryByDocumentIdReviewsData,
  PostApiLibraryByDocumentIdReviewsResponse,
  PostApiLibraryByDocumentIdReviewsError,
  GetApiMarketplaceCatalogData,
  GetApiMarketplaceCatalogResponse,
  GetApiMarketplaceSearchData,
  GetApiMarketplaceSearchResponse,
  GetApiMarketplaceDocumentsByIdData,
  GetApiMarketplaceDocumentsByIdResponse,
  GetApiMarketplaceDocumentsByIdError,
  GetApiMarketplaceDocumentsByIdPreviewData,
  GetApiMarketplaceDocumentsByIdPreviewResponse,
  GetApiMarketplaceDocumentsByIdPreviewError,
  GetApiMarketplaceDocumentsByIdRelatedData,
  GetApiMarketplaceDocumentsByIdRelatedResponse,
  GetApiMarketplaceCategoriesData,
  GetApiMarketplaceCategoriesResponse,
  GetApiMarketplaceCategoriesBySlugData,
  GetApiMarketplaceCategoriesBySlugResponse,
  GetApiMarketplaceCategoriesBySlugError,
  GetApiMarketplaceFreeData,
  GetApiMarketplaceFreeResponse,
  GetApiMarketplaceBundlesData,
  GetApiMarketplaceBundlesResponse,
  GetApiMarketplaceBundlesByIdData,
  GetApiMarketplaceBundlesByIdResponse,
  GetApiMarketplaceBundlesByIdError,
  GetApiMeProfileData,
  GetApiMeProfileResponse,
  GetApiMeProfileError,
  PutApiMeProfileData,
  PutApiMeProfileResponse,
  PutApiMeProfileError,
  GetApiNotificationsSettingsData,
  GetApiNotificationsSettingsResponse,
  GetApiNotificationsSettingsError,
  PutApiNotificationsSettingsData,
  PutApiNotificationsSettingsResponse,
  PutApiNotificationsSettingsError,
  PostApiWebhooksOmiseData,
  GetApiOrdersData,
  GetApiOrdersResponse,
  PostApiOrdersData,
  PostApiOrdersResponse,
  PostApiOrdersError,
  GetApiOrdersByIdData,
  GetApiOrdersByIdResponse,
  GetApiOrdersByIdError,
  GetApiPaymentsOmisePublicConfigData,
  GetApiPaymentsOmisePublicConfigResponse,
  GetApiSellerDashboardData,
  GetApiSellerDashboardResponse,
  PostApiSellerDocumentsByIdAiGenerateData,
  PostApiSellerDocumentsByIdAiGenerateResponse,
  PostApiSellerDocumentsByIdAiGenerateError,
  GetApiSellerEarningsData,
  GetApiSellerEarningsResponse,
  GetApiSellerReviewsData,
  GetApiSellerReviewsResponse,
  GetApiSellerDocumentsData,
  GetApiSellerDocumentsResponse,
  PostApiSellerDocumentsData,
  PostApiSellerDocumentsResponse,
  PostApiSellerDocumentsError,
  DeleteApiSellerDocumentsByIdData,
  DeleteApiSellerDocumentsByIdResponse,
  DeleteApiSellerDocumentsByIdError,
  GetApiSellerDocumentsByIdData,
  GetApiSellerDocumentsByIdResponse,
  GetApiSellerDocumentsByIdError,
  PutApiSellerDocumentsByIdData,
  PutApiSellerDocumentsByIdResponse,
  PutApiSellerDocumentsByIdError,
  PostApiSellerDocumentsByIdPreviewRasterData,
  PostApiSellerDocumentsByIdPreviewRasterError,
  PostApiSellerDocumentsByIdGeneratePreviewData,
  PostApiSellerDocumentsByIdGeneratePreviewResponse,
  PostApiSellerDocumentsByIdGeneratePreviewError,
  GetApiSellerDocumentsByIdMainFilesData,
  GetApiSellerDocumentsByIdMainFilesResponse,
  GetApiSellerDocumentsByIdMainFilesError,
  PostApiSellerDocumentsByIdMainFilesData,
  PostApiSellerDocumentsByIdMainFilesResponse,
  PostApiSellerDocumentsByIdMainFilesError,
  PutApiSellerDocumentsByIdListedMainFileData,
  PutApiSellerDocumentsByIdListedMainFileResponse,
  PutApiSellerDocumentsByIdListedMainFileError,
  GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlData,
  GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlResponse,
  GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlError,
  GetApiSellerDocumentsByIdDownloadUrlData,
  GetApiSellerDocumentsByIdDownloadUrlResponse,
  GetApiSellerDocumentsByIdDownloadUrlError,
  GetApiSellersBySellerIdProfileData,
  GetApiSellersBySellerIdProfileResponse,
  GetApiSellersBySellerIdProfileError,
  DeleteApiSellersBySellerIdFollowData,
  DeleteApiSellersBySellerIdFollowResponse,
  GetApiSellersBySellerIdFollowData,
  GetApiSellersBySellerIdFollowResponse,
  PostApiSellersBySellerIdFollowData,
  GetApiSystemStatusData,
  GetApiSystemStatusResponse,
  GetApiSystemR2Data,
  DeleteApiWishlistData,
  DeleteApiWishlistResponse,
  GetApiWishlistData,
  GetApiWishlistResponse,
  PostApiWishlistData,
  PostApiWishlistResponse,
  PostApiWishlistError,
  DeleteApiWishlistByDocumentIdData,
  DeleteApiWishlistByDocumentIdResponse,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getApiAdminDashboard = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminDashboardData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiAdminDashboardResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/dashboard',
    ...options,
  });
};

export const getApiAdminTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminTransactionsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiAdminTransactionsResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/transactions',
    ...options,
  });
};

export const getApiAdminDocuments = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiAdminDocumentsResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/documents',
    ...options,
  });
};

export const getApiAdminDocumentsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAdminDocumentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiAdminDocumentsByIdResponse,
    GetApiAdminDocumentsByIdError,
    ThrowOnError
  >({
    url: '/api/admin/documents/{id}',
    ...options,
  });
};

export const patchApiAdminDocumentsById = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiAdminDocumentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchApiAdminDocumentsByIdResponse,
    PatchApiAdminDocumentsByIdError,
    ThrowOnError
  >({
    url: '/api/admin/documents/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiAdminDocumentsBulk = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminDocumentsBulkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAdminDocumentsBulkResponse,
    PostApiAdminDocumentsBulkError,
    ThrowOnError
  >({
    url: '/api/admin/documents/bulk',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getApiAdminDocumentsByIdReports = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAdminDocumentsByIdReportsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiAdminDocumentsByIdReportsResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/documents/{id}/reports',
    ...options,
  });
};

export const postApiAdminDocumentsByIdReports = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminDocumentsByIdReportsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAdminDocumentsByIdReportsResponse,
    PostApiAdminDocumentsByIdReportsError,
    ThrowOnError
  >({
    url: '/api/admin/documents/{id}/reports',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiAdminDocumentsByIdReportsByReportIdResolve = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiAdminDocumentsByIdReportsByReportIdResolveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAdminDocumentsByIdReportsByReportIdResolveResponse,
    PostApiAdminDocumentsByIdReportsByReportIdResolveError,
    ThrowOnError
  >({
    url: '/api/admin/documents/{id}/reports/{reportId}/resolve',
    ...options,
  });
};

export const postApiAdminDocumentsByIdReportsResolveAll = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminDocumentsByIdReportsResolveAllData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAdminDocumentsByIdReportsResolveAllResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/documents/{id}/reports/resolve-all',
    ...options,
  });
};

export const getApiAdminDocumentsPending = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminDocumentsPendingData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiAdminDocumentsPendingResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/documents/pending',
    ...options,
  });
};

export const postApiAdminDocumentsPendingSearch = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminDocumentsPendingSearchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAdminDocumentsPendingSearchResponse,
    PostApiAdminDocumentsPendingSearchError,
    ThrowOnError
  >({
    url: '/api/admin/documents/pending/search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiAdminDocumentsByIdApprove = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminDocumentsByIdApproveData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAdminDocumentsByIdApproveResponse,
    PostApiAdminDocumentsByIdApproveError,
    ThrowOnError
  >({
    url: '/api/admin/documents/{id}/approve',
    ...options,
  });
};

export const postApiAdminDocumentsByIdReject = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminDocumentsByIdRejectData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAdminDocumentsByIdRejectResponse,
    PostApiAdminDocumentsByIdRejectError,
    ThrowOnError
  >({
    url: '/api/admin/documents/{id}/reject',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getApiAdminSellers = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminSellersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiAdminSellersResponse, unknown, ThrowOnError>({
    url: '/api/admin/sellers',
    ...options,
  });
};

export const getApiAdminSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminSettingsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiAdminSettingsResponse, unknown, ThrowOnError>(
    {
      url: '/api/admin/settings',
      ...options,
    },
  );
};

export const putApiAdminSettings = <ThrowOnError extends boolean = false>(
  options: Options<PutApiAdminSettingsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiAdminSettingsResponse,
    PutApiAdminSettingsError,
    ThrowOnError
  >({
    url: '/api/admin/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getApiAdminStorageUsage = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminStorageUsageData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiAdminStorageUsageResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/storage/usage',
    ...options,
  });
};

export const getApiAuthOauthClients = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthOauthClientsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiAuthOauthClientsResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/auth/oauth-clients',
    ...options,
  });
};

export const postApiAuthRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthRegisterData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAuthRegisterResponse,
    PostApiAuthRegisterError,
    ThrowOnError
  >({
    url: '/api/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiAuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthLoginData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAuthLoginResponse,
    PostApiAuthLoginError,
    ThrowOnError
  >({
    url: '/api/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiAuthRefresh = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthRefreshData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAuthRefreshResponse,
    PostApiAuthRefreshError,
    ThrowOnError
  >({
    url: '/api/auth/refresh',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiAuthLogout = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthLogoutData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<PostApiAuthLogoutResponse, unknown, ThrowOnError>({
    url: '/api/auth/logout',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiAuthVerifyEmail = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthVerifyEmailData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAuthVerifyEmailResponse,
    PostApiAuthVerifyEmailError,
    ThrowOnError
  >({
    url: '/api/auth/verify-email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiAuthResendVerification = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthResendVerificationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAuthResendVerificationResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/auth/resend-verification',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiAuthExternalByProvider = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthExternalByProviderData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAuthExternalByProviderResponse,
    PostApiAuthExternalByProviderError,
    ThrowOnError
  >({
    url: '/api/auth/external/{provider}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const deleteApiCart = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteApiCartData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).delete<DeleteApiCartResponse, unknown, ThrowOnError>({
    url: '/api/cart',
    ...options,
  });
};

export const getApiCart = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiCartData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiCartResponse, unknown, ThrowOnError>({
    url: '/api/cart',
    ...options,
  });
};

export const postApiCartItems = <ThrowOnError extends boolean = false>(
  options: Options<PostApiCartItemsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiCartItemsResponse,
    PostApiCartItemsError,
    ThrowOnError
  >({
    url: '/api/cart/items',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const deleteApiCartItemsByDocumentId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiCartItemsByDocumentIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiCartItemsByDocumentIdResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/cart/items/{documentId}',
    ...options,
  });
};

export const getApiAdminCategories = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminCategoriesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiAdminCategoriesResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/admin/categories',
    ...options,
  });
};

export const postApiAdminCategories = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminCategoriesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAdminCategoriesResponse,
    PostApiAdminCategoriesError,
    ThrowOnError
  >({
    url: '/api/admin/categories',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const deleteApiAdminCategoriesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiAdminCategoriesByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiAdminCategoriesByIdResponse,
    DeleteApiAdminCategoriesByIdError,
    ThrowOnError
  >({
    url: '/api/admin/categories/{id}',
    ...options,
  });
};

export const getApiAdminCategoriesById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAdminCategoriesByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiAdminCategoriesByIdResponse,
    GetApiAdminCategoriesByIdError,
    ThrowOnError
  >({
    url: '/api/admin/categories/{id}',
    ...options,
  });
};

export const putApiAdminCategoriesById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiAdminCategoriesByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiAdminCategoriesByIdResponse,
    PutApiAdminCategoriesByIdError,
    ThrowOnError
  >({
    url: '/api/admin/categories/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiDocumentUpload = <ThrowOnError extends boolean = false>(
  options: Options<PostApiDocumentUploadData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiDocumentUploadResponse,
    PostApiDocumentUploadError,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/api/document/upload',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });
};

export const postApiFilesUpload = <ThrowOnError extends boolean = false>(
  options: Options<PostApiFilesUploadData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<PostApiFilesUploadResponse, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/files/upload',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });
};

export const postApiFilesUploadBase64 = <ThrowOnError extends boolean = false>(
  options: Options<PostApiFilesUploadBase64Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiFilesUploadBase64Response,
    unknown,
    ThrowOnError
  >({
    url: '/api/files/upload-base64',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getApiFilesDownloadByKey = <ThrowOnError extends boolean = false>(
  options: Options<GetApiFilesDownloadByKeyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/api/files/download/{key}',
    ...options,
  });
};

export const getApiFilesPresignedByKey = <ThrowOnError extends boolean = false>(
  options: Options<GetApiFilesPresignedByKeyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/api/files/presigned/{key}',
    ...options,
  });
};

export const getApiLibrary = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiLibraryData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiLibraryResponse, unknown, ThrowOnError>({
    url: '/api/library',
    ...options,
  });
};

export const postApiLibraryByDocumentIdDownload = <ThrowOnError extends boolean = false>(
  options: Options<PostApiLibraryByDocumentIdDownloadData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiLibraryByDocumentIdDownloadResponse,
    PostApiLibraryByDocumentIdDownloadError,
    ThrowOnError
  >({
    url: '/api/library/{documentId}/download',
    ...options,
  });
};

export const postApiLibraryByDocumentIdReviews = <ThrowOnError extends boolean = false>(
  options: Options<PostApiLibraryByDocumentIdReviewsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiLibraryByDocumentIdReviewsResponse,
    PostApiLibraryByDocumentIdReviewsError,
    ThrowOnError
  >({
    url: '/api/library/{documentId}/reviews',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getApiMarketplaceCatalog = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiMarketplaceCatalogData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiMarketplaceCatalogResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/marketplace/catalog',
    ...options,
  });
};

export const getApiMarketplaceSearch = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiMarketplaceSearchData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiMarketplaceSearchResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/marketplace/search',
    ...options,
  });
};

export const getApiMarketplaceDocumentsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMarketplaceDocumentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiMarketplaceDocumentsByIdResponse,
    GetApiMarketplaceDocumentsByIdError,
    ThrowOnError
  >({
    url: '/api/marketplace/documents/{id}',
    ...options,
  });
};

export const getApiMarketplaceDocumentsByIdPreview = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMarketplaceDocumentsByIdPreviewData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiMarketplaceDocumentsByIdPreviewResponse,
    GetApiMarketplaceDocumentsByIdPreviewError,
    ThrowOnError
  >({
    url: '/api/marketplace/documents/{id}/preview',
    ...options,
  });
};

export const getApiMarketplaceDocumentsByIdRelated = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMarketplaceDocumentsByIdRelatedData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiMarketplaceDocumentsByIdRelatedResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/marketplace/documents/{id}/related',
    ...options,
  });
};

export const getApiMarketplaceCategories = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiMarketplaceCategoriesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiMarketplaceCategoriesResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/marketplace/categories',
    ...options,
  });
};

export const getApiMarketplaceCategoriesBySlug = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMarketplaceCategoriesBySlugData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiMarketplaceCategoriesBySlugResponse,
    GetApiMarketplaceCategoriesBySlugError,
    ThrowOnError
  >({
    url: '/api/marketplace/categories/{slug}',
    ...options,
  });
};

export const getApiMarketplaceFree = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiMarketplaceFreeData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiMarketplaceFreeResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/marketplace/free',
    ...options,
  });
};

export const getApiMarketplaceBundles = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiMarketplaceBundlesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiMarketplaceBundlesResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/marketplace/bundles',
    ...options,
  });
};

export const getApiMarketplaceBundlesById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMarketplaceBundlesByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiMarketplaceBundlesByIdResponse,
    GetApiMarketplaceBundlesByIdError,
    ThrowOnError
  >({
    url: '/api/marketplace/bundles/{id}',
    ...options,
  });
};

export const getApiMeProfile = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiMeProfileData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiMeProfileResponse,
    GetApiMeProfileError,
    ThrowOnError
  >({
    url: '/api/me/profile',
    ...options,
  });
};

export const putApiMeProfile = <ThrowOnError extends boolean = false>(
  options: Options<PutApiMeProfileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiMeProfileResponse,
    PutApiMeProfileError,
    ThrowOnError
  >({
    url: '/api/me/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getApiNotificationsSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiNotificationsSettingsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiNotificationsSettingsResponse,
    GetApiNotificationsSettingsError,
    ThrowOnError
  >({
    url: '/api/notifications/settings',
    ...options,
  });
};

export const putApiNotificationsSettings = <ThrowOnError extends boolean = false>(
  options: Options<PutApiNotificationsSettingsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiNotificationsSettingsResponse,
    PutApiNotificationsSettingsError,
    ThrowOnError
  >({
    url: '/api/notifications/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiWebhooksOmise = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiWebhooksOmiseData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: '/api/webhooks/omise',
    ...options,
  });
};

export const getApiOrders = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiOrdersResponse, unknown, ThrowOnError>({
    url: '/api/orders',
    ...options,
  });
};

export const postApiOrders = <ThrowOnError extends boolean = false>(
  options: Options<PostApiOrdersData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiOrdersResponse,
    PostApiOrdersError,
    ThrowOnError
  >({
    url: '/api/orders',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getApiOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiOrdersByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiOrdersByIdResponse,
    GetApiOrdersByIdError,
    ThrowOnError
  >({
    url: '/api/orders/{id}',
    ...options,
  });
};

export const getApiPaymentsOmisePublicConfig = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPaymentsOmisePublicConfigData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiPaymentsOmisePublicConfigResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/payments/omise-public-config',
    ...options,
  });
};

export const getApiSellerDashboard = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSellerDashboardData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiSellerDashboardResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/seller/dashboard',
    ...options,
  });
};

export const postApiSellerDocumentsByIdAiGenerate = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSellerDocumentsByIdAiGenerateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiSellerDocumentsByIdAiGenerateResponse,
    PostApiSellerDocumentsByIdAiGenerateError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}/ai-generate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getApiSellerEarnings = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSellerEarningsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiSellerEarningsResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/seller/earnings',
    ...options,
  });
};

export const getApiSellerReviews = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSellerReviewsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiSellerReviewsResponse, unknown, ThrowOnError>(
    {
      url: '/api/seller/reviews',
      ...options,
    },
  );
};

export const getApiSellerDocuments = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSellerDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiSellerDocumentsResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/seller/documents',
    ...options,
  });
};

export const postApiSellerDocuments = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSellerDocumentsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiSellerDocumentsResponse,
    PostApiSellerDocumentsError,
    ThrowOnError
  >({
    url: '/api/seller/documents',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const deleteApiSellerDocumentsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiSellerDocumentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiSellerDocumentsByIdResponse,
    DeleteApiSellerDocumentsByIdError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}',
    ...options,
  });
};

export const getApiSellerDocumentsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSellerDocumentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiSellerDocumentsByIdResponse,
    GetApiSellerDocumentsByIdError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}',
    ...options,
  });
};

export const putApiSellerDocumentsById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiSellerDocumentsByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiSellerDocumentsByIdResponse,
    PutApiSellerDocumentsByIdError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postApiSellerDocumentsByIdPreviewRaster = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSellerDocumentsByIdPreviewRasterData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    PostApiSellerDocumentsByIdPreviewRasterError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}/preview-raster',
    ...options,
  });
};

export const postApiSellerDocumentsByIdGeneratePreview = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSellerDocumentsByIdGeneratePreviewData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiSellerDocumentsByIdGeneratePreviewResponse,
    PostApiSellerDocumentsByIdGeneratePreviewError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}/generate-preview',
    ...options,
  });
};

export const getApiSellerDocumentsByIdMainFiles = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSellerDocumentsByIdMainFilesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiSellerDocumentsByIdMainFilesResponse,
    GetApiSellerDocumentsByIdMainFilesError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}/main-files',
    ...options,
  });
};

export const postApiSellerDocumentsByIdMainFiles = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSellerDocumentsByIdMainFilesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiSellerDocumentsByIdMainFilesResponse,
    PostApiSellerDocumentsByIdMainFilesError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}/main-files',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const putApiSellerDocumentsByIdListedMainFile = <ThrowOnError extends boolean = false>(
  options: Options<PutApiSellerDocumentsByIdListedMainFileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiSellerDocumentsByIdListedMainFileResponse,
    PutApiSellerDocumentsByIdListedMainFileError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}/listed-main-file',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getApiSellerDocumentsByIdMainFilesByFileIdDownloadUrl = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlResponse,
    GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}/main-files/{fileId}/download-url',
    ...options,
  });
};

export const getApiSellerDocumentsByIdDownloadUrl = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSellerDocumentsByIdDownloadUrlData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiSellerDocumentsByIdDownloadUrlResponse,
    GetApiSellerDocumentsByIdDownloadUrlError,
    ThrowOnError
  >({
    url: '/api/seller/documents/{id}/download-url',
    ...options,
  });
};

export const getApiSellersBySellerIdProfile = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSellersBySellerIdProfileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiSellersBySellerIdProfileResponse,
    GetApiSellersBySellerIdProfileError,
    ThrowOnError
  >({
    url: '/api/sellers/{sellerId}/profile',
    ...options,
  });
};

export const deleteApiSellersBySellerIdFollow = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiSellersBySellerIdFollowData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiSellersBySellerIdFollowResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/sellers/{sellerId}/follow',
    ...options,
  });
};

export const getApiSellersBySellerIdFollow = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSellersBySellerIdFollowData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiSellersBySellerIdFollowResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/sellers/{sellerId}/follow',
    ...options,
  });
};

export const postApiSellersBySellerIdFollow = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSellersBySellerIdFollowData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: '/api/sellers/{sellerId}/follow',
    ...options,
  });
};

export const getApiSystemStatus = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSystemStatusData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiSystemStatusResponse, unknown, ThrowOnError>({
    url: '/api/system/status',
    ...options,
  });
};

export const getApiSystemR2 = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSystemR2Data, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/api/system/r2',
    ...options,
  });
};

export const deleteApiWishlist = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteApiWishlistData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).delete<
    DeleteApiWishlistResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/wishlist',
    ...options,
  });
};

export const getApiWishlist = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiWishlistData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiWishlistResponse, unknown, ThrowOnError>({
    url: '/api/wishlist',
    ...options,
  });
};

export const postApiWishlist = <ThrowOnError extends boolean = false>(
  options: Options<PostApiWishlistData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiWishlistResponse,
    PostApiWishlistError,
    ThrowOnError
  >({
    url: '/api/wishlist',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const deleteApiWishlistByDocumentId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiWishlistByDocumentIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiWishlistByDocumentIdResponse,
    unknown,
    ThrowOnError
  >({
    url: '/api/wishlist/{documentId}',
    ...options,
  });
};
