// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5282/SIRIEDUMARKET.Api' | (string & {});
};

export type AddSellerDocumentMainFileRequest = {
  storageKey: string;
  originalFileName?: string | null;
};

export type AddToCartRequest = {
  documentId: string;
};

export type AddToWishlistRequest = {
  documentId?: string | null;
  bundleId?: string | null;
};

export type AdminAuditEntryResponse = {
  id?: string;
  actorUserId?: string | null;
  action?: string;
  detailsJson?: string | null;
  createdAt?: string;
};

export type AdminBulkDocumentsRequest = {
  documentIds: Array<string>;
  action: string;
  reason?: string | null;
};

export type AdminBulkDocumentsResponse = {
  processedCount?: number;
  failedIds?: Array<string>;
};

export type AdminDashboardResponse = {
  totalRevenue?: number;
  totalFees?: number;
  successCount?: number;
  refundCount?: number;
  totalDocuments?: number;
  totalSellers?: number;
  totalBuyers?: number;
  pendingApproval?: number;
  serviceStatus?: Array<ServiceStatusItem>;
};

export type AdminDocumentActionResponse = {
  documentId?: string;
  status?: string;
  processedAt?: string;
};

export type AdminDocumentDetailResponse = {
  id?: string;
  slug?: string;
  title?: string;
  shortDescription?: string;
  description?: string;
  coverUrl?: string;
  galleryUrls?: Array<string>;
  galleryItems?: Array<SellerDocumentGalleryItemResponse>;
  price?: number;
  format?: string;
  status?: string;
  rejectionReason?: string | null;
  categoryIds?: Array<string>;
  subcategoryId?: string | null;
  resourceType?: string;
  sellerId?: string;
  sellerName?: string;
  isFeatured?: boolean;
  isFree?: boolean;
  watermarkEnabled?: boolean;
  previewPages?: number;
  pages?: number;
  fileSize?: string;
  language?: string;
  fileStorageKey?: string | null;
  previewStorageKey?: string | null;
  tags?: Array<string>;
  gradeLevels?: Array<string>;
  standards?: Array<string>;
  openReportCount?: number;
  createdAt?: string;
  updatedAt?: string;
  recentAudit?: Array<AdminAuditEntryResponse>;
  mainFiles?: Array<SellerDocumentMainFileResponse>;
  listedMainFileId?: string | null;
};

export type AdminDocumentListItemResponse = {
  id?: string;
  title?: string;
  shortDescription?: string;
  coverUrl?: string | null;
  sellerName?: string;
  sellerId?: string;
  categoryIds?: Array<string>;
  format?: string;
  status?: string;
  price?: number;
  isFeatured?: boolean;
  isFree?: boolean;
  openReportCount?: number;
  createdAt?: string;
  updatedAt?: string;
};

export type AdminDocumentReportResponse = {
  id?: string;
  reason?: string;
  createdAt?: string;
  resolvedAt?: string | null;
  resolvedByUserId?: string | null;
};

export type AdminDocumentsSort = number;

export type AdminPayoutResponse = {
  sellerId?: string;
  sellerName?: string;
  sellerEmail?: string;
  requestedAt?: string;
  id?: string;
  grossAmount?: number;
  fee?: number;
  netAmount?: number;
  status?: string;
  bankAccount?: string | null;
  periodStart?: string;
  periodEnd?: string;
  paidAt?: string | null;
};

export type AdminPendingDocumentResponse = {
  id?: string;
  title?: string;
  shortDescription?: string;
  coverUrl?: string | null;
  sellerName?: string;
  categoryIds?: Array<string>;
  format?: string;
  price?: number;
  submittedAt?: string;
};

export type AdminPendingDocumentsSearchRequest = {
  title?: string | null;
  sellerName?: string | null;
  postedFrom?: string | null;
  postedTo?: string | null;
  page?: number;
  pageSize?: number;
};

export type AdminPendingDocumentsSort = number;

export type AdminSellerApplicationResponse = {
  userId?: string;
  studioName?: string;
  bio?: string;
  specialties?: Array<string>;
  ownerName?: string;
  email?: string;
  avatarUrl?: string | null;
  status?: string;
  appliedAt?: string | null;
};

export type AdminSellerResponse = {
  id?: string;
  studioName?: string;
  ownerName?: string;
  email?: string;
  avatarUrl?: string | null;
  isVerified?: boolean;
  totalDocuments?: number;
  totalSales?: number;
  totalRevenue?: number;
  joinedAt?: string;
};

export type AdminTransactionResponse = {
  id?: string;
  orderNumber?: string;
  buyerName?: string;
  sellerName?: string;
  documentTitle?: string;
  amount?: number;
  fee?: number;
  netAmount?: number;
  paymentMethod?: string;
  status?: string;
  createdAt?: string;
};

export type AnswerDocumentQuestionRequest = {
  answer: string;
};

export type AskDocumentQuestionRequest = {
  question: string;
};

export type AuthActionResponse = {
  message: string;
};

export type AuthSessionResponse = {
  accessToken: string;
  accessTokenExpiresAt: string;
  refreshToken: string;
  user: AuthUserResponse;
};

export type AuthUserResponse = {
  id: string;
  email: string;
  displayName: string;
  isEmailVerified: boolean;
  role: string;
};

export type BundleDetailResponse = {
  id?: string;
  slug?: string;
  title?: string;
  description?: string;
  coverUrl?: string;
  price?: number;
  originalPrice?: number;
  averageRating?: number;
  reviewCount?: number;
  downloads?: number;
  seller?: SellerInfoResponse;
  documents?: Array<MarketplaceDocumentResponse>;
  createdAt?: string;
};

export type BundleResponse = {
  id?: string;
  slug?: string;
  title?: string;
  description?: string;
  coverUrl?: string;
  price?: number;
  originalPrice?: number;
  documentCount?: number;
  averageRating?: number;
  reviewCount?: number;
  downloads?: number;
  sellerId?: string;
  sellerName?: string;
  createdAt?: string;
};

export type CartItemResponse = {
  documentId?: string;
  title?: string;
  sellerName?: string;
  price?: number;
  coverUrl?: string;
};

export type CartResponse = {
  items?: Array<CartItemResponse>;
  subtotal?: number;
  serviceFee?: number;
  vatIncluded?: number;
  total?: number;
};

export type CategoryDetailResponse = {
  id?: string;
  name?: string;
  slug?: string;
  icon?: string;
  color?: string;
  description?: string;
  documentCount?: number;
  subcategories?: Array<SubcategoryResponse>;
};

export type CategoryResponse = {
  id?: string;
  name?: string;
  slug?: string;
  icon?: string;
  color?: string;
  description?: string;
  isActive?: boolean;
  sortOrder?: number;
  documentCount?: number;
};

export type CreateCategoryRequest = {
  id: string;
  name: string;
  slug?: string;
  icon?: string;
  color?: string;
  description?: string;
  isActive?: boolean;
  sortOrder?: number;
};

export type CreateDocumentReportRequest = {
  reason: string;
};

export type CreateDocumentRequest = {
  title: string;
  shortDescription?: string;
  description?: string;
  price: number;
  categoryIds: Array<string>;
  subcategoryId?: string | null;
  isFree?: boolean;
  format: string;
  tags?: Array<string>;
  gradeLevels?: Array<string>;
  resourceType?: string;
  standards?: Array<string>;
  watermarkEnabled?: boolean;
  previewWatermarkSubtitle?: string | null;
  previewWatermarkFontFamily?: string | null;
  language?: string;
};

export type CreateOrderRequest = {
  [key: string]: unknown;
};

export type DocumentGalleryItemRequest = {
  id?: string | null;
  imageUrl?: string;
};

export type DocumentQnaResponse = {
  id?: string;
  buyerName?: string;
  buyerAvatarUrl?: string | null;
  question?: string;
  askedAt?: string;
  answerText?: string | null;
  answeredAt?: string | null;
};

export type DocumentReviewWriteResponse = {
  id?: string;
  documentId?: string;
  rating?: number;
  comment?: string;
  createdAt?: string;
  updatedAt?: string | null;
};

export type DocumentUploadResponse = {
  documentId: string;
  previewImageUrls: Array<string>;
};

export type DownloadTokenResponse = {
  downloadUrl?: string;
  expiresAt?: string;
};

export type ExternalLoginRequest = {
  authorizationCode: string;
  redirectUri?: string | null;
};

export type ForgotPasswordRequest = {
  email: string;
};

export type GeneratePreviewResponse = {
  previewStorageKey: string;
  previewPublicUrl: string | null;
};

export type IFormFile = Blob | File;

export type LibraryItemResponse = {
  documentId?: string;
  title?: string;
  coverUrl?: string | null;
  format?: string;
  orderNumber?: string;
  purchasedAt?: string;
  downloadCount?: number;
  lastDownloadAt?: string | null;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type LogoutRequest = {
  refreshToken: string;
};

export type MarketplaceCatalogResponse = {
  categories?: Array<MarketplaceCategoryResponse>;
  documents?: PagedResponseOfMarketplaceDocumentResponse;
};

export type MarketplaceCategoryResponse = {
  id?: string;
  label?: string;
  count?: number;
};

export type MarketplaceDocumentDetailResponse = {
  id?: string;
  slug?: string;
  title?: string;
  shortDescription?: string;
  description?: string;
  coverUrl?: string;
  galleryUrls?: Array<string>;
  price?: number;
  originalPrice?: number | null;
  discountPercent?: number | null;
  format?: string;
  pages?: number;
  fileSize?: string;
  language?: string;
  categoryIds?: Array<string>;
  subcategoryId?: string | null;
  gradeLevels?: Array<string>;
  resourceType?: string;
  standards?: Array<string>;
  tags?: Array<string>;
  averageRating?: number;
  reviewCount?: number;
  downloads?: number;
  status?: string;
  watermarkEnabled?: boolean;
  previewPages?: number;
  previewStorageKey?: string | null;
  seller?: SellerInfoResponse;
  createdAt?: string;
  updatedAt?: string;
  reviews?: Array<MarketplaceDocumentReviewResponse>;
  qna?: Array<DocumentQnaResponse>;
  aiSummary?: Array<string> | null;
  aiHighlights?: Array<string> | null;
  isFree?: boolean;
  isBestseller?: boolean;
  isFeatured?: boolean;
  isEditorsPick?: boolean;
  bundleIds?: Array<string> | null;
};

export type MarketplaceDocumentPreviewResponse = {
  documentId?: string;
  watermark?: string;
  excerptTitle?: string;
  excerptLines?: Array<string>;
  previewImageUrls?: Array<string>;
};

export type MarketplaceDocumentResponse = {
  id?: string;
  slug?: string;
  title?: string;
  shortDescription?: string;
  sellerName?: string;
  price?: number;
  originalPrice?: number | null;
  averageRating?: number;
  reviewCount?: number;
  categoryIds?: Array<string>;
  coverUrl?: string;
  galleryCount?: number;
  galleryPreviewUrls?: Array<string>;
  pages?: number;
  format?: string;
  isFree?: boolean;
  isBestseller?: boolean;
  isFeatured?: boolean;
  topReviews?: Array<MarketplaceDocumentReviewResponse>;
};

export type MarketplaceDocumentReviewResponse = {
  id?: string;
  authorName?: string;
  rating?: number;
  comment?: string;
  createdAt?: string;
};

export type MarketplaceSearchResponse = {
  items?: Array<MarketplaceDocumentResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type NotificationSettingResponse = {
  key?: string;
  label?: string;
  isEnabled?: boolean;
};

export type OrderItemResponse = {
  id?: string;
  documentId?: string | null;
  bundleId?: string | null;
  title?: string;
  coverUrl?: string | null;
  priceAtPurchase?: number;
};

export type OrderPaymentHintsResponse = {
  stripePaymentIntentId?: string | null;
  clientSecret?: string | null;
  status?: string | null;
  awaitingWebhook?: boolean;
};

export type OrderResponse = {
  id?: string;
  orderNumber?: string;
  total?: number;
  subTotal?: number;
  vatAmount?: number;
  status?: string;
  paymentMethod?: string;
  createdAt?: string;
  paidAt?: string | null;
  items?: Array<OrderItemResponse>;
  paymentHints?: OrderPaymentHintsResponse | null;
};

export type PagedResponseOfAdminDocumentListItemResponse = {
  items?: Array<AdminDocumentListItemResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfAdminPayoutResponse = {
  items?: Array<AdminPayoutResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfAdminPendingDocumentResponse = {
  items?: Array<AdminPendingDocumentResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfAdminSellerApplicationResponse = {
  items?: Array<AdminSellerApplicationResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfAdminSellerResponse = {
  items?: Array<AdminSellerResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfAdminTransactionResponse = {
  items?: Array<AdminTransactionResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfBundleResponse = {
  items?: Array<BundleResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfLibraryItemResponse = {
  items?: Array<LibraryItemResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfMarketplaceDocumentResponse = {
  items?: Array<MarketplaceDocumentResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfOrderResponse = {
  items?: Array<OrderResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfSellerDocumentSummaryResponse = {
  items?: Array<SellerDocumentSummaryResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfSellerQnaResponse = {
  items?: Array<SellerQnaResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfSellerReviewResponse = {
  items?: Array<SellerReviewResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PagedResponseOfWishlistItemResponse = {
  items?: Array<WishlistItemResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
};

export type PatchAdminDocumentRequest = {
  title?: string | null;
  shortDescription?: string | null;
  description?: string | null;
  price?: number | null;
  categoryIds?: Array<string> | null;
  subcategoryId?: string | null;
  resourceType?: string | null;
  format?: string | null;
  status?: string | null;
  tags?: Array<string> | null;
  gradeLevels?: Array<string> | null;
  standards?: Array<string> | null;
  isFeatured?: boolean | null;
  isFree?: boolean | null;
  watermarkEnabled?: boolean | null;
  previewPages?: number | null;
  pages?: number | null;
  fileSize?: string | null;
  language?: string | null;
  galleryImageUrls?: Array<string> | null;
  galleryItems?: Array<DocumentGalleryItemRequest> | null;
  fileStorageKey?: string | null;
  previewStorageKey?: string | null;
};

export type PayoutResponse = {
  id?: string;
  grossAmount?: number;
  fee?: number;
  netAmount?: number;
  status?: string;
  bankAccount?: string | null;
  periodStart?: string;
  periodEnd?: string;
  paidAt?: string | null;
};

export type PlatformSettingsResponse = {
  feeRatePercent?: number;
  vatPercent?: number;
  payoutMinTHB?: number;
  payoutSchedule?: string;
};

export type PresignedUrlResponse = {
  url: string;
  expiresSeconds: number;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
};

export type PublicOAuthClientsResponse = {
  googleClientId?: string;
};

export type RefreshTokenRequest = {
  refreshToken: string;
};

export type RegisterRequest = {
  email: string;
  password: string;
  confirmPassword: string;
  displayName: string;
};

export type RejectDocumentRequest = {
  reason: string;
};

export type RejectSellerApplicationRequest = {
  reason: string;
};

export type RequestPayoutRequest = {
  bankAccount: string;
};

export type ResendVerificationEmailRequest = {
  email: string;
};

export type ResetPasswordRequest = {
  token: string;
  password: string;
  confirmPassword: string;
};

export type RevenueByMonthItem = {
  month?: string;
  amount?: number;
};

export type SaveBundleRequest = {
  title: string;
  description: string;
  coverUrl?: string;
  price?: number;
  documentIds?: Array<string>;
};

export type SaveStoreSectionRequest = {
  name: string;
  sortOrder?: number;
  documentIds?: Array<string>;
};

export type SellerApplicationResponse = {
  userId?: string;
  studioName?: string;
  bio?: string;
  specialties?: Array<string>;
  status?: string;
  rejectionReason?: string | null;
  appliedAt?: string | null;
  reviewedAt?: string | null;
};

export type SellerBundleItemResponse = {
  documentId?: string;
  title?: string;
  price?: number;
  coverUrl?: string;
};

export type SellerBundleResponse = {
  id?: string;
  slug?: string;
  title?: string;
  description?: string;
  coverUrl?: string;
  price?: number;
  originalPrice?: number;
  downloadCount?: number;
  canDelete?: boolean;
  items?: Array<SellerBundleItemResponse>;
  createdAt?: string;
  updatedAt?: string;
};

export type SellerDashboardResponse = {
  totalRevenue?: number;
  monthlyRevenue?: number;
  totalDownloads?: number;
  monthlyDownloads?: number;
  averageRating?: number;
  totalReviews?: number;
  pendingPayout?: number;
  activeListings?: number;
  pendingApproval?: number;
  followerCount?: number;
  newFollowersThisMonth?: number;
  revenueByMonth?: Array<RevenueByMonthItem>;
  topCategories?: Array<TopCategoryItem>;
};

export type SellerDocumentGalleryItemResponse = {
  id?: string;
  imageUrl?: string;
};

export type SellerDocumentMainFileResponse = {
  id?: string;
  storageKey?: string;
  originalFileName?: string;
  uploadedAt?: string;
  isListedForSale?: boolean;
};

export type SellerDocumentResponse = {
  id?: string;
  slug?: string;
  title?: string;
  shortDescription?: string;
  coverUrl?: string | null;
  galleryImageUrls?: Array<string>;
  galleryItems?: Array<SellerDocumentGalleryItemResponse>;
  galleryCount?: number;
  galleryPreviewUrls?: Array<string>;
  price?: number;
  format?: string;
  pages?: number;
  fileSize?: string;
  language?: string;
  status?: string;
  averageRating?: number;
  reviewCount?: number;
  downloads?: number;
  salesCount?: number;
  previewPages?: number;
  watermarkEnabled?: boolean;
  previewWatermarkSubtitle?: string | null;
  previewWatermarkFontFamily?: string | null;
  categoryIds?: Array<string>;
  isFree?: boolean;
  createdAt?: string;
  updatedAt?: string;
  mainFiles?: Array<SellerDocumentMainFileResponse>;
  listedMainFileId?: string | null;
};

export type SellerDocumentSummaryResponse = {
  id?: string;
  slug?: string;
  title?: string;
  coverUrl?: string | null;
  price?: number;
  format?: string;
  pages?: number;
  status?: string;
  averageRating?: number;
  reviewCount?: number;
  downloads?: number;
  salesCount?: number;
  updatedAt?: string;
};

export type SellerEarningsResponse = {
  totalEarnings?: number;
  pendingBalance?: number;
  payouts?: Array<PayoutResponse>;
};

export type SellerFollowStatusResponse = {
  isFollowing?: boolean;
};

export type SellerInfoResponse = {
  id?: string;
  studioName?: string;
  ownerName?: string;
  avatarUrl?: string | null;
  bannerUrl?: string | null;
  bio?: string;
  joinedAt?: string;
  rating?: number;
  totalSales?: number;
  totalDocuments?: number;
  followerCount?: number;
  responseHours?: number;
  badges?: Array<string>;
  specialties?: Array<string> | null;
};

export type SellerProfileResponse = {
  id?: string;
  studioName?: string;
  ownerName?: string;
  avatarUrl?: string | null;
  bannerUrl?: string | null;
  bio?: string;
  joinedAt?: string;
  rating?: number;
  totalSales?: number;
  totalDocuments?: number;
  followerCount?: number;
  responseHours?: number;
  isVerified?: boolean;
  badges?: Array<string>;
  specialties?: Array<string> | null;
  isFollowing?: boolean;
  storeSections?: Array<StoreSectionResponse>;
};

export type SellerProfileSummary = {
  studioName?: string;
  isVerified?: boolean;
};

export type SellerQnaResponse = {
  id?: string;
  documentId?: string;
  documentTitle?: string;
  buyerName?: string;
  question?: string;
  askedAt?: string;
  answerText?: string | null;
  answeredAt?: string | null;
};

export type SellerReviewResponse = {
  id?: string;
  documentId?: string;
  documentTitle?: string;
  buyerName?: string;
  buyerAvatarUrl?: string | null;
  rating?: number;
  comment?: string;
  isVerified?: boolean;
  helpfulCount?: number;
  sellerReplyText?: string | null;
  sellerRepliedAt?: string | null;
  createdAt?: string;
};

export type ServiceStatusItem = {
  name?: string;
  status?: string;
  message?: string | null;
};

export type SetListedSellerDocumentMainFileRequest = {
  fileId: string;
};

export type StorageUsageResponse = {
  bucketName?: string;
  objectCount?: number;
  totalBytes?: number;
  isConfigured?: boolean;
};

export type StoreSectionResponse = {
  id?: string;
  name?: string;
  sortOrder?: number;
  documentIds?: Array<string>;
};

export type StripePublicConfigResponse = {
  publishableKey?: string;
};

export type SubcategoryResponse = {
  id?: string;
  categoryId?: string;
  name?: string;
  slug?: string;
  icon?: string | null;
  documentCount?: number;
};

export type SubmitDocumentReviewRequest = {
  rating?: number;
  comment: string;
};

export type SubmitSellerApplicationRequest = {
  studioName: string;
  bio?: string;
  specialties?: Array<string>;
};

export type SystemStatusResponse = {
  name: string;
  environment: string;
  version: string;
  status: string;
  generatedAtUtc: string;
};

export type TestEmailRequest = {
  to: string;
  displayName: string | null;
};

export type TopCategoryItem = {
  category?: string;
  sales?: number;
};

export type UpdateCategoryRequest = {
  name: string;
  slug?: string;
  icon?: string;
  color?: string;
  description?: string;
  isActive?: boolean;
  sortOrder?: number;
};

export type UpdateDocumentRequest = {
  title?: string | null;
  shortDescription?: string | null;
  description?: string | null;
  price?: number | null;
  categoryIds?: Array<string> | null;
  subcategoryId?: string | null;
  isFree?: boolean | null;
  format?: string | null;
  tags?: Array<string> | null;
  gradeLevels?: Array<string> | null;
  resourceType?: string | null;
  standards?: Array<string> | null;
  watermarkEnabled?: boolean | null;
  language?: string | null;
  fileStorageKey?: string | null;
  previewStorageKey?: string | null;
  pages?: number | null;
  previewPages?: number | null;
  fileSize?: string | null;
  previewWatermarkSubtitle?: string | null;
  previewWatermarkFontFamily?: string | null;
  galleryImageUrls?: Array<string> | null;
  galleryItems?: Array<DocumentGalleryItemRequest> | null;
};

export type UpdateNotificationSettingsRequest = {
  settings?: {
    [key: string]: boolean;
  };
};

export type UpdatePayoutStatusRequest = {
  status: string;
};

export type UpdatePlatformSettingsRequest = {
  feeRatePercent?: number;
  vatPercent?: number;
  payoutMinTHB?: number;
  payoutSchedule: string;
};

export type UpdateProfileRequest = {
  name?: string | null;
  avatarUrl?: string | null;
};

export type UploadBase64Request = {
  name: string;
  base64: string;
  contentType: string | null;
};

export type UploadResponse = {
  key: string;
  publicUrl: string;
  eTag: string;
};

export type UserProfileResponse = {
  id?: string;
  name?: string;
  email?: string;
  avatarUrl?: string | null;
  role?: string;
  joinedAt?: string;
  isEmailVerified?: boolean;
  sellerProfile?: SellerProfileSummary | null;
};

export type VerifyEmailRequest = {
  token: string;
};

export type WishlistItemResponse = {
  documentId?: string | null;
  bundleId?: string | null;
  title?: string;
  coverUrl?: string | null;
  price?: number;
  originalPrice?: number | null;
  sellerName?: string;
  addedAt?: string;
  format?: string | null;
  averageRating?: number | null;
};

export type GetApiAdminDashboardData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/dashboard';
};

export type GetApiAdminDashboardResponses = {
  /**
   * OK
   */
  200: AdminDashboardResponse;
};

export type GetApiAdminDashboardResponse =
  GetApiAdminDashboardResponses[keyof GetApiAdminDashboardResponses];

export type GetApiAdminTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/admin/transactions';
};

export type GetApiAdminTransactionsResponses = {
  /**
   * OK
   */
  200: PagedResponseOfAdminTransactionResponse;
};

export type GetApiAdminTransactionsResponse =
  GetApiAdminTransactionsResponses[keyof GetApiAdminTransactionsResponses];

export type GetApiAdminDocumentsData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
    Status?: string;
    Format?: string;
    CategoryId?: string;
    SellerName?: string;
    Q?: string;
    FeaturedOnly?: boolean;
    HasOpenReportsOnly?: boolean;
    PostedFrom?: string;
    PostedTo?: string;
    Sort?: AdminDocumentsSort;
  };
  url: '/api/admin/documents';
};

export type GetApiAdminDocumentsResponses = {
  /**
   * OK
   */
  200: PagedResponseOfAdminDocumentListItemResponse;
};

export type GetApiAdminDocumentsResponse =
  GetApiAdminDocumentsResponses[keyof GetApiAdminDocumentsResponses];

export type GetApiAdminDocumentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/documents/{id}';
};

export type GetApiAdminDocumentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiAdminDocumentsByIdError =
  GetApiAdminDocumentsByIdErrors[keyof GetApiAdminDocumentsByIdErrors];

export type GetApiAdminDocumentsByIdResponses = {
  /**
   * OK
   */
  200: AdminDocumentDetailResponse;
};

export type GetApiAdminDocumentsByIdResponse =
  GetApiAdminDocumentsByIdResponses[keyof GetApiAdminDocumentsByIdResponses];

export type PatchApiAdminDocumentsByIdData = {
  body: PatchAdminDocumentRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/documents/{id}';
};

export type PatchApiAdminDocumentsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PatchApiAdminDocumentsByIdError =
  PatchApiAdminDocumentsByIdErrors[keyof PatchApiAdminDocumentsByIdErrors];

export type PatchApiAdminDocumentsByIdResponses = {
  /**
   * OK
   */
  200: AdminDocumentDetailResponse;
};

export type PatchApiAdminDocumentsByIdResponse =
  PatchApiAdminDocumentsByIdResponses[keyof PatchApiAdminDocumentsByIdResponses];

export type PostApiAdminDocumentsBulkData = {
  body: AdminBulkDocumentsRequest;
  path?: never;
  query?: never;
  url: '/api/admin/documents/bulk';
};

export type PostApiAdminDocumentsBulkErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiAdminDocumentsBulkError =
  PostApiAdminDocumentsBulkErrors[keyof PostApiAdminDocumentsBulkErrors];

export type PostApiAdminDocumentsBulkResponses = {
  /**
   * OK
   */
  200: AdminBulkDocumentsResponse;
};

export type PostApiAdminDocumentsBulkResponse =
  PostApiAdminDocumentsBulkResponses[keyof PostApiAdminDocumentsBulkResponses];

export type GetApiAdminDocumentsByIdReportsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/documents/{id}/reports';
};

export type GetApiAdminDocumentsByIdReportsResponses = {
  /**
   * OK
   */
  200: Array<AdminDocumentReportResponse>;
};

export type GetApiAdminDocumentsByIdReportsResponse =
  GetApiAdminDocumentsByIdReportsResponses[keyof GetApiAdminDocumentsByIdReportsResponses];

export type PostApiAdminDocumentsByIdReportsData = {
  body: CreateDocumentReportRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/documents/{id}/reports';
};

export type PostApiAdminDocumentsByIdReportsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiAdminDocumentsByIdReportsError =
  PostApiAdminDocumentsByIdReportsErrors[keyof PostApiAdminDocumentsByIdReportsErrors];

export type PostApiAdminDocumentsByIdReportsResponses = {
  /**
   * Created
   */
  201: AdminDocumentReportResponse;
};

export type PostApiAdminDocumentsByIdReportsResponse =
  PostApiAdminDocumentsByIdReportsResponses[keyof PostApiAdminDocumentsByIdReportsResponses];

export type PostApiAdminDocumentsByIdReportsByReportIdResolveData = {
  body?: never;
  path: {
    id: string;
    reportId: string;
  };
  query?: never;
  url: '/api/admin/documents/{id}/reports/{reportId}/resolve';
};

export type PostApiAdminDocumentsByIdReportsByReportIdResolveErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiAdminDocumentsByIdReportsByReportIdResolveError =
  PostApiAdminDocumentsByIdReportsByReportIdResolveErrors[keyof PostApiAdminDocumentsByIdReportsByReportIdResolveErrors];

export type PostApiAdminDocumentsByIdReportsByReportIdResolveResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAdminDocumentsByIdReportsByReportIdResolveResponse =
  PostApiAdminDocumentsByIdReportsByReportIdResolveResponses[keyof PostApiAdminDocumentsByIdReportsByReportIdResolveResponses];

export type PostApiAdminDocumentsByIdReportsResolveAllData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/documents/{id}/reports/resolve-all';
};

export type PostApiAdminDocumentsByIdReportsResolveAllResponses = {
  /**
   * OK
   */
  200: number;
};

export type PostApiAdminDocumentsByIdReportsResolveAllResponse =
  PostApiAdminDocumentsByIdReportsResolveAllResponses[keyof PostApiAdminDocumentsByIdReportsResolveAllResponses];

export type GetApiAdminDocumentsPendingData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
    Title?: string;
    SellerName?: string;
    PostedFrom?: string;
    PostedTo?: string;
    TitleContains?: string;
    SellerNameContains?: string;
    SubmittedFrom?: string;
    SubmittedTo?: string;
    Sort?: AdminPendingDocumentsSort;
  };
  url: '/api/admin/documents/pending';
};

export type GetApiAdminDocumentsPendingResponses = {
  /**
   * OK
   */
  200: PagedResponseOfAdminPendingDocumentResponse;
};

export type GetApiAdminDocumentsPendingResponse =
  GetApiAdminDocumentsPendingResponses[keyof GetApiAdminDocumentsPendingResponses];

export type PostApiAdminDocumentsPendingSearchData = {
  body: AdminPendingDocumentsSearchRequest;
  path?: never;
  query?: never;
  url: '/api/admin/documents/pending/search';
};

export type PostApiAdminDocumentsPendingSearchErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiAdminDocumentsPendingSearchError =
  PostApiAdminDocumentsPendingSearchErrors[keyof PostApiAdminDocumentsPendingSearchErrors];

export type PostApiAdminDocumentsPendingSearchResponses = {
  /**
   * OK
   */
  200: PagedResponseOfAdminPendingDocumentResponse;
};

export type PostApiAdminDocumentsPendingSearchResponse =
  PostApiAdminDocumentsPendingSearchResponses[keyof PostApiAdminDocumentsPendingSearchResponses];

export type PostApiAdminDocumentsByIdApproveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/documents/{id}/approve';
};

export type PostApiAdminDocumentsByIdApproveErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiAdminDocumentsByIdApproveError =
  PostApiAdminDocumentsByIdApproveErrors[keyof PostApiAdminDocumentsByIdApproveErrors];

export type PostApiAdminDocumentsByIdApproveResponses = {
  /**
   * OK
   */
  200: AdminDocumentActionResponse;
};

export type PostApiAdminDocumentsByIdApproveResponse =
  PostApiAdminDocumentsByIdApproveResponses[keyof PostApiAdminDocumentsByIdApproveResponses];

export type PostApiAdminDocumentsByIdRejectData = {
  body: RejectDocumentRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/documents/{id}/reject';
};

export type PostApiAdminDocumentsByIdRejectErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiAdminDocumentsByIdRejectError =
  PostApiAdminDocumentsByIdRejectErrors[keyof PostApiAdminDocumentsByIdRejectErrors];

export type PostApiAdminDocumentsByIdRejectResponses = {
  /**
   * OK
   */
  200: AdminDocumentActionResponse;
};

export type PostApiAdminDocumentsByIdRejectResponse =
  PostApiAdminDocumentsByIdRejectResponses[keyof PostApiAdminDocumentsByIdRejectResponses];

export type GetApiAdminSellersData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/admin/sellers';
};

export type GetApiAdminSellersResponses = {
  /**
   * OK
   */
  200: PagedResponseOfAdminSellerResponse;
};

export type GetApiAdminSellersResponse =
  GetApiAdminSellersResponses[keyof GetApiAdminSellersResponses];

export type GetApiAdminSellerApplicationsData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/admin/seller-applications';
};

export type GetApiAdminSellerApplicationsResponses = {
  /**
   * OK
   */
  200: PagedResponseOfAdminSellerApplicationResponse;
};

export type GetApiAdminSellerApplicationsResponse =
  GetApiAdminSellerApplicationsResponses[keyof GetApiAdminSellerApplicationsResponses];

export type PostApiAdminSellerApplicationsByUserIdApproveData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: never;
  url: '/api/admin/seller-applications/{userId}/approve';
};

export type PostApiAdminSellerApplicationsByUserIdApproveErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiAdminSellerApplicationsByUserIdApproveError =
  PostApiAdminSellerApplicationsByUserIdApproveErrors[keyof PostApiAdminSellerApplicationsByUserIdApproveErrors];

export type PostApiAdminSellerApplicationsByUserIdApproveResponses = {
  /**
   * OK
   */
  200: SellerApplicationResponse;
};

export type PostApiAdminSellerApplicationsByUserIdApproveResponse =
  PostApiAdminSellerApplicationsByUserIdApproveResponses[keyof PostApiAdminSellerApplicationsByUserIdApproveResponses];

export type PostApiAdminSellerApplicationsByUserIdRejectData = {
  body: RejectSellerApplicationRequest;
  path: {
    userId: string;
  };
  query?: never;
  url: '/api/admin/seller-applications/{userId}/reject';
};

export type PostApiAdminSellerApplicationsByUserIdRejectErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiAdminSellerApplicationsByUserIdRejectError =
  PostApiAdminSellerApplicationsByUserIdRejectErrors[keyof PostApiAdminSellerApplicationsByUserIdRejectErrors];

export type PostApiAdminSellerApplicationsByUserIdRejectResponses = {
  /**
   * OK
   */
  200: SellerApplicationResponse;
};

export type PostApiAdminSellerApplicationsByUserIdRejectResponse =
  PostApiAdminSellerApplicationsByUserIdRejectResponses[keyof PostApiAdminSellerApplicationsByUserIdRejectResponses];

export type GetApiAdminPayoutsData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
    status?: string;
  };
  url: '/api/admin/payouts';
};

export type GetApiAdminPayoutsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type GetApiAdminPayoutsError = GetApiAdminPayoutsErrors[keyof GetApiAdminPayoutsErrors];

export type GetApiAdminPayoutsResponses = {
  /**
   * OK
   */
  200: PagedResponseOfAdminPayoutResponse;
};

export type GetApiAdminPayoutsResponse =
  GetApiAdminPayoutsResponses[keyof GetApiAdminPayoutsResponses];

export type PostApiAdminPayoutsByPayoutIdStatusData = {
  body: UpdatePayoutStatusRequest;
  path: {
    payoutId: string;
  };
  query?: never;
  url: '/api/admin/payouts/{payoutId}/status';
};

export type PostApiAdminPayoutsByPayoutIdStatusErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiAdminPayoutsByPayoutIdStatusError =
  PostApiAdminPayoutsByPayoutIdStatusErrors[keyof PostApiAdminPayoutsByPayoutIdStatusErrors];

export type PostApiAdminPayoutsByPayoutIdStatusResponses = {
  /**
   * OK
   */
  200: AdminPayoutResponse;
};

export type PostApiAdminPayoutsByPayoutIdStatusResponse =
  PostApiAdminPayoutsByPayoutIdStatusResponses[keyof PostApiAdminPayoutsByPayoutIdStatusResponses];

export type GetApiAdminSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/settings';
};

export type GetApiAdminSettingsResponses = {
  /**
   * OK
   */
  200: PlatformSettingsResponse;
};

export type GetApiAdminSettingsResponse =
  GetApiAdminSettingsResponses[keyof GetApiAdminSettingsResponses];

export type PutApiAdminSettingsData = {
  body: UpdatePlatformSettingsRequest;
  path?: never;
  query?: never;
  url: '/api/admin/settings';
};

export type PutApiAdminSettingsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PutApiAdminSettingsError = PutApiAdminSettingsErrors[keyof PutApiAdminSettingsErrors];

export type PutApiAdminSettingsResponses = {
  /**
   * OK
   */
  200: PlatformSettingsResponse;
};

export type PutApiAdminSettingsResponse =
  PutApiAdminSettingsResponses[keyof PutApiAdminSettingsResponses];

export type GetApiAdminStorageUsageData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/storage/usage';
};

export type GetApiAdminStorageUsageResponses = {
  /**
   * OK
   */
  200: StorageUsageResponse;
};

export type GetApiAdminStorageUsageResponse =
  GetApiAdminStorageUsageResponses[keyof GetApiAdminStorageUsageResponses];

export type GetApiAuthOauthClientsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/oauth-clients';
};

export type GetApiAuthOauthClientsResponses = {
  /**
   * OK
   */
  200: PublicOAuthClientsResponse;
};

export type GetApiAuthOauthClientsResponse =
  GetApiAuthOauthClientsResponses[keyof GetApiAuthOauthClientsResponses];

export type PostApiAuthRegisterData = {
  body: RegisterRequest;
  path?: never;
  query?: never;
  url: '/api/auth/register';
};

export type PostApiAuthRegisterErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiAuthRegisterError = PostApiAuthRegisterErrors[keyof PostApiAuthRegisterErrors];

export type PostApiAuthRegisterResponses = {
  /**
   * Created
   */
  201: AuthActionResponse;
};

export type PostApiAuthRegisterResponse =
  PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type PostApiAuthLoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
  /**
   * OK
   */
  200: AuthSessionResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRefreshData = {
  body: RefreshTokenRequest;
  path?: never;
  query?: never;
  url: '/api/auth/refresh';
};

export type PostApiAuthRefreshErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiAuthRefreshError = PostApiAuthRefreshErrors[keyof PostApiAuthRefreshErrors];

export type PostApiAuthRefreshResponses = {
  /**
   * OK
   */
  200: AuthSessionResponse;
};

export type PostApiAuthRefreshResponse =
  PostApiAuthRefreshResponses[keyof PostApiAuthRefreshResponses];

export type PostApiAuthLogoutData = {
  body: LogoutRequest;
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type PostApiAuthLogoutResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiAuthLogoutResponse =
  PostApiAuthLogoutResponses[keyof PostApiAuthLogoutResponses];

export type PostApiAuthVerifyEmailData = {
  body: VerifyEmailRequest;
  path?: never;
  query?: never;
  url: '/api/auth/verify-email';
};

export type PostApiAuthVerifyEmailErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiAuthVerifyEmailError =
  PostApiAuthVerifyEmailErrors[keyof PostApiAuthVerifyEmailErrors];

export type PostApiAuthVerifyEmailResponses = {
  /**
   * OK
   */
  200: AuthSessionResponse;
};

export type PostApiAuthVerifyEmailResponse =
  PostApiAuthVerifyEmailResponses[keyof PostApiAuthVerifyEmailResponses];

export type PostApiAuthResendVerificationData = {
  body: ResendVerificationEmailRequest;
  path?: never;
  query?: never;
  url: '/api/auth/resend-verification';
};

export type PostApiAuthResendVerificationResponses = {
  /**
   * OK
   */
  200: AuthActionResponse;
};

export type PostApiAuthResendVerificationResponse =
  PostApiAuthResendVerificationResponses[keyof PostApiAuthResendVerificationResponses];

export type PostApiAuthForgotPasswordData = {
  body: ForgotPasswordRequest;
  path?: never;
  query?: never;
  url: '/api/auth/forgot-password';
};

export type PostApiAuthForgotPasswordResponses = {
  /**
   * OK
   */
  200: AuthActionResponse;
};

export type PostApiAuthForgotPasswordResponse =
  PostApiAuthForgotPasswordResponses[keyof PostApiAuthForgotPasswordResponses];

export type PostApiAuthResetPasswordData = {
  body: ResetPasswordRequest;
  path?: never;
  query?: never;
  url: '/api/auth/reset-password';
};

export type PostApiAuthResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiAuthResetPasswordError =
  PostApiAuthResetPasswordErrors[keyof PostApiAuthResetPasswordErrors];

export type PostApiAuthResetPasswordResponses = {
  /**
   * OK
   */
  200: AuthActionResponse;
};

export type PostApiAuthResetPasswordResponse =
  PostApiAuthResetPasswordResponses[keyof PostApiAuthResetPasswordResponses];

export type PostApiAuthExternalByProviderData = {
  body: ExternalLoginRequest;
  path: {
    provider: string;
  };
  query?: never;
  url: '/api/auth/external/{provider}';
};

export type PostApiAuthExternalByProviderErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Implemented
   */
  501: unknown;
};

export type PostApiAuthExternalByProviderError =
  PostApiAuthExternalByProviderErrors[keyof PostApiAuthExternalByProviderErrors];

export type PostApiAuthExternalByProviderResponses = {
  /**
   * OK
   */
  200: AuthSessionResponse;
};

export type PostApiAuthExternalByProviderResponse =
  PostApiAuthExternalByProviderResponses[keyof PostApiAuthExternalByProviderResponses];

export type DeleteApiCartData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/cart';
};

export type DeleteApiCartResponses = {
  /**
   * OK
   */
  200: CartResponse;
};

export type DeleteApiCartResponse = DeleteApiCartResponses[keyof DeleteApiCartResponses];

export type GetApiCartData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/cart';
};

export type GetApiCartResponses = {
  /**
   * OK
   */
  200: CartResponse;
};

export type GetApiCartResponse = GetApiCartResponses[keyof GetApiCartResponses];

export type PostApiCartItemsData = {
  body: AddToCartRequest;
  path?: never;
  query?: never;
  url: '/api/cart/items';
};

export type PostApiCartItemsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiCartItemsError = PostApiCartItemsErrors[keyof PostApiCartItemsErrors];

export type PostApiCartItemsResponses = {
  /**
   * OK
   */
  200: CartResponse;
};

export type PostApiCartItemsResponse = PostApiCartItemsResponses[keyof PostApiCartItemsResponses];

export type PostApiCartBundlesByBundleIdData = {
  body?: never;
  path: {
    bundleId: string;
  };
  query?: never;
  url: '/api/cart/bundles/{bundleId}';
};

export type PostApiCartBundlesByBundleIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostApiCartBundlesByBundleIdError =
  PostApiCartBundlesByBundleIdErrors[keyof PostApiCartBundlesByBundleIdErrors];

export type PostApiCartBundlesByBundleIdResponses = {
  /**
   * OK
   */
  200: CartResponse;
};

export type PostApiCartBundlesByBundleIdResponse =
  PostApiCartBundlesByBundleIdResponses[keyof PostApiCartBundlesByBundleIdResponses];

export type DeleteApiCartItemsByDocumentIdData = {
  body?: never;
  path: {
    documentId: string;
  };
  query?: never;
  url: '/api/cart/items/{documentId}';
};

export type DeleteApiCartItemsByDocumentIdResponses = {
  /**
   * OK
   */
  200: CartResponse;
};

export type DeleteApiCartItemsByDocumentIdResponse =
  DeleteApiCartItemsByDocumentIdResponses[keyof DeleteApiCartItemsByDocumentIdResponses];

export type GetApiAdminCategoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/admin/categories';
};

export type GetApiAdminCategoriesResponses = {
  /**
   * OK
   */
  200: Array<CategoryResponse>;
};

export type GetApiAdminCategoriesResponse =
  GetApiAdminCategoriesResponses[keyof GetApiAdminCategoriesResponses];

export type PostApiAdminCategoriesData = {
  body: CreateCategoryRequest;
  path?: never;
  query?: never;
  url: '/api/admin/categories';
};

export type PostApiAdminCategoriesErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiAdminCategoriesError =
  PostApiAdminCategoriesErrors[keyof PostApiAdminCategoriesErrors];

export type PostApiAdminCategoriesResponses = {
  /**
   * Created
   */
  201: CategoryResponse;
};

export type PostApiAdminCategoriesResponse =
  PostApiAdminCategoriesResponses[keyof PostApiAdminCategoriesResponses];

export type DeleteApiAdminCategoriesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/categories/{id}';
};

export type DeleteApiAdminCategoriesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteApiAdminCategoriesByIdError =
  DeleteApiAdminCategoriesByIdErrors[keyof DeleteApiAdminCategoriesByIdErrors];

export type DeleteApiAdminCategoriesByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiAdminCategoriesByIdResponse =
  DeleteApiAdminCategoriesByIdResponses[keyof DeleteApiAdminCategoriesByIdResponses];

export type GetApiAdminCategoriesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/categories/{id}';
};

export type GetApiAdminCategoriesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiAdminCategoriesByIdError =
  GetApiAdminCategoriesByIdErrors[keyof GetApiAdminCategoriesByIdErrors];

export type GetApiAdminCategoriesByIdResponses = {
  /**
   * OK
   */
  200: CategoryResponse;
};

export type GetApiAdminCategoriesByIdResponse =
  GetApiAdminCategoriesByIdResponses[keyof GetApiAdminCategoriesByIdResponses];

export type PutApiAdminCategoriesByIdData = {
  body: UpdateCategoryRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/admin/categories/{id}';
};

export type PutApiAdminCategoriesByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutApiAdminCategoriesByIdError =
  PutApiAdminCategoriesByIdErrors[keyof PutApiAdminCategoriesByIdErrors];

export type PutApiAdminCategoriesByIdResponses = {
  /**
   * OK
   */
  200: CategoryResponse;
};

export type PutApiAdminCategoriesByIdResponse =
  PutApiAdminCategoriesByIdResponses[keyof PutApiAdminCategoriesByIdResponses];

export type PostApiDocumentUploadData = {
  body: {
    file?: IFormFile;
  };
  path?: never;
  query?: never;
  url: '/api/document/upload';
};

export type PostApiDocumentUploadErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiDocumentUploadError =
  PostApiDocumentUploadErrors[keyof PostApiDocumentUploadErrors];

export type PostApiDocumentUploadResponses = {
  /**
   * OK
   */
  200: DocumentUploadResponse;
};

export type PostApiDocumentUploadResponse =
  PostApiDocumentUploadResponses[keyof PostApiDocumentUploadResponses];

export type PostApiFilesUploadData = {
  body: {
    file?: IFormFile;
  };
  path?: never;
  query?: never;
  url: '/api/files/upload';
};

export type PostApiFilesUploadResponses = {
  /**
   * OK
   */
  200: UploadResponse;
};

export type PostApiFilesUploadResponse =
  PostApiFilesUploadResponses[keyof PostApiFilesUploadResponses];

export type PostApiFilesUploadBase64Data = {
  body: UploadBase64Request;
  path?: never;
  query?: never;
  url: '/api/files/upload-base64';
};

export type PostApiFilesUploadBase64Responses = {
  /**
   * OK
   */
  200: UploadResponse;
};

export type PostApiFilesUploadBase64Response =
  PostApiFilesUploadBase64Responses[keyof PostApiFilesUploadBase64Responses];

export type GetApiFilesDownloadByKeyData = {
  body?: never;
  path: {
    key: string;
  };
  query?: never;
  url: '/api/files/download/{key}';
};

export type GetApiFilesDownloadByKeyErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiFilesDownloadByKeyError =
  GetApiFilesDownloadByKeyErrors[keyof GetApiFilesDownloadByKeyErrors];

export type GetApiFilesPresignedByKeyData = {
  body?: never;
  path: {
    key: string;
  };
  query?: {
    expiresSeconds?: number;
  };
  url: '/api/files/presigned/{key}';
};

export type GetApiFilesPresignedByKeyErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiFilesPresignedByKeyError =
  GetApiFilesPresignedByKeyErrors[keyof GetApiFilesPresignedByKeyErrors];

export type GetApiLibraryData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/library';
};

export type GetApiLibraryResponses = {
  /**
   * OK
   */
  200: PagedResponseOfLibraryItemResponse;
};

export type GetApiLibraryResponse = GetApiLibraryResponses[keyof GetApiLibraryResponses];

export type PostApiLibraryByDocumentIdDownloadData = {
  body?: never;
  path: {
    documentId: string;
  };
  query?: never;
  url: '/api/library/{documentId}/download';
};

export type PostApiLibraryByDocumentIdDownloadErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiLibraryByDocumentIdDownloadError =
  PostApiLibraryByDocumentIdDownloadErrors[keyof PostApiLibraryByDocumentIdDownloadErrors];

export type PostApiLibraryByDocumentIdDownloadResponses = {
  /**
   * OK
   */
  200: DownloadTokenResponse;
};

export type PostApiLibraryByDocumentIdDownloadResponse =
  PostApiLibraryByDocumentIdDownloadResponses[keyof PostApiLibraryByDocumentIdDownloadResponses];

export type PostApiLibraryByDocumentIdReviewsData = {
  body: SubmitDocumentReviewRequest;
  path: {
    documentId: string;
  };
  query?: never;
  url: '/api/library/{documentId}/reviews';
};

export type PostApiLibraryByDocumentIdReviewsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiLibraryByDocumentIdReviewsError =
  PostApiLibraryByDocumentIdReviewsErrors[keyof PostApiLibraryByDocumentIdReviewsErrors];

export type PostApiLibraryByDocumentIdReviewsResponses = {
  /**
   * OK
   */
  200: DocumentReviewWriteResponse;
};

export type PostApiLibraryByDocumentIdReviewsResponse =
  PostApiLibraryByDocumentIdReviewsResponses[keyof PostApiLibraryByDocumentIdReviewsResponses];

export type PostApiMarketplaceDocumentsByIdQnaData = {
  body: AskDocumentQuestionRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/marketplace/documents/{id}/qna';
};

export type PostApiMarketplaceDocumentsByIdQnaErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiMarketplaceDocumentsByIdQnaError =
  PostApiMarketplaceDocumentsByIdQnaErrors[keyof PostApiMarketplaceDocumentsByIdQnaErrors];

export type PostApiMarketplaceDocumentsByIdQnaResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostApiMarketplaceDocumentsByIdQnaResponse =
  PostApiMarketplaceDocumentsByIdQnaResponses[keyof PostApiMarketplaceDocumentsByIdQnaResponses];

export type GetApiMarketplaceCatalogData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/marketplace/catalog';
};

export type GetApiMarketplaceCatalogResponses = {
  /**
   * OK
   */
  200: MarketplaceCatalogResponse;
};

export type GetApiMarketplaceCatalogResponse =
  GetApiMarketplaceCatalogResponses[keyof GetApiMarketplaceCatalogResponses];

export type GetApiMarketplaceSearchData = {
  body?: never;
  path?: never;
  query?: {
    Q?: string;
    CategoryId?: string;
    SubcategoryId?: string;
    SellerId?: string;
    Sort?: string;
    Page?: number;
    PageSize?: number;
    FreeOnly?: boolean;
    MinPrice?: number;
    MaxPrice?: number;
    Format?: string;
    GradeLevel?: string;
    ResourceType?: string;
    Standard?: string;
  };
  url: '/api/marketplace/search';
};

export type GetApiMarketplaceSearchResponses = {
  /**
   * OK
   */
  200: MarketplaceSearchResponse;
};

export type GetApiMarketplaceSearchResponse =
  GetApiMarketplaceSearchResponses[keyof GetApiMarketplaceSearchResponses];

export type GetApiMarketplaceDocumentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/marketplace/documents/{id}';
};

export type GetApiMarketplaceDocumentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiMarketplaceDocumentsByIdError =
  GetApiMarketplaceDocumentsByIdErrors[keyof GetApiMarketplaceDocumentsByIdErrors];

export type GetApiMarketplaceDocumentsByIdResponses = {
  /**
   * OK
   */
  200: MarketplaceDocumentDetailResponse;
};

export type GetApiMarketplaceDocumentsByIdResponse =
  GetApiMarketplaceDocumentsByIdResponses[keyof GetApiMarketplaceDocumentsByIdResponses];

export type GetApiMarketplaceDocumentsByIdPreviewData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/marketplace/documents/{id}/preview';
};

export type GetApiMarketplaceDocumentsByIdPreviewErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiMarketplaceDocumentsByIdPreviewError =
  GetApiMarketplaceDocumentsByIdPreviewErrors[keyof GetApiMarketplaceDocumentsByIdPreviewErrors];

export type GetApiMarketplaceDocumentsByIdPreviewResponses = {
  /**
   * OK
   */
  200: MarketplaceDocumentPreviewResponse;
};

export type GetApiMarketplaceDocumentsByIdPreviewResponse =
  GetApiMarketplaceDocumentsByIdPreviewResponses[keyof GetApiMarketplaceDocumentsByIdPreviewResponses];

export type GetApiMarketplaceDocumentsByIdRelatedData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/marketplace/documents/{id}/related';
};

export type GetApiMarketplaceDocumentsByIdRelatedResponses = {
  /**
   * OK
   */
  200: PagedResponseOfMarketplaceDocumentResponse;
};

export type GetApiMarketplaceDocumentsByIdRelatedResponse =
  GetApiMarketplaceDocumentsByIdRelatedResponses[keyof GetApiMarketplaceDocumentsByIdRelatedResponses];

export type GetApiMarketplaceCategoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/marketplace/categories';
};

export type GetApiMarketplaceCategoriesResponses = {
  /**
   * OK
   */
  200: Array<CategoryResponse>;
};

export type GetApiMarketplaceCategoriesResponse =
  GetApiMarketplaceCategoriesResponses[keyof GetApiMarketplaceCategoriesResponses];

export type GetApiMarketplaceCategoriesBySlugData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/marketplace/categories/{slug}';
};

export type GetApiMarketplaceCategoriesBySlugErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiMarketplaceCategoriesBySlugError =
  GetApiMarketplaceCategoriesBySlugErrors[keyof GetApiMarketplaceCategoriesBySlugErrors];

export type GetApiMarketplaceCategoriesBySlugResponses = {
  /**
   * OK
   */
  200: CategoryDetailResponse;
};

export type GetApiMarketplaceCategoriesBySlugResponse =
  GetApiMarketplaceCategoriesBySlugResponses[keyof GetApiMarketplaceCategoriesBySlugResponses];

export type GetApiMarketplaceFreeData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/marketplace/free';
};

export type GetApiMarketplaceFreeResponses = {
  /**
   * OK
   */
  200: PagedResponseOfMarketplaceDocumentResponse;
};

export type GetApiMarketplaceFreeResponse =
  GetApiMarketplaceFreeResponses[keyof GetApiMarketplaceFreeResponses];

export type GetApiMarketplaceBundlesData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/marketplace/bundles';
};

export type GetApiMarketplaceBundlesResponses = {
  /**
   * OK
   */
  200: PagedResponseOfBundleResponse;
};

export type GetApiMarketplaceBundlesResponse =
  GetApiMarketplaceBundlesResponses[keyof GetApiMarketplaceBundlesResponses];

export type GetApiMarketplaceBundlesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/marketplace/bundles/{id}';
};

export type GetApiMarketplaceBundlesByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiMarketplaceBundlesByIdError =
  GetApiMarketplaceBundlesByIdErrors[keyof GetApiMarketplaceBundlesByIdErrors];

export type GetApiMarketplaceBundlesByIdResponses = {
  /**
   * OK
   */
  200: BundleDetailResponse;
};

export type GetApiMarketplaceBundlesByIdResponse =
  GetApiMarketplaceBundlesByIdResponses[keyof GetApiMarketplaceBundlesByIdResponses];

export type GetApiMeProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/me/profile';
};

export type GetApiMeProfileErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiMeProfileError = GetApiMeProfileErrors[keyof GetApiMeProfileErrors];

export type GetApiMeProfileResponses = {
  /**
   * OK
   */
  200: UserProfileResponse;
};

export type GetApiMeProfileResponse = GetApiMeProfileResponses[keyof GetApiMeProfileResponses];

export type PutApiMeProfileData = {
  body: UpdateProfileRequest;
  path?: never;
  query?: never;
  url: '/api/me/profile';
};

export type PutApiMeProfileErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutApiMeProfileError = PutApiMeProfileErrors[keyof PutApiMeProfileErrors];

export type PutApiMeProfileResponses = {
  /**
   * OK
   */
  200: UserProfileResponse;
};

export type PutApiMeProfileResponse = PutApiMeProfileResponses[keyof PutApiMeProfileResponses];

export type GetApiMeSellerApplicationData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/me/seller-application';
};

export type GetApiMeSellerApplicationErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiMeSellerApplicationError =
  GetApiMeSellerApplicationErrors[keyof GetApiMeSellerApplicationErrors];

export type GetApiMeSellerApplicationResponses = {
  /**
   * OK
   */
  200: SellerApplicationResponse;
};

export type GetApiMeSellerApplicationResponse =
  GetApiMeSellerApplicationResponses[keyof GetApiMeSellerApplicationResponses];

export type PostApiMeSellerApplicationData = {
  body: SubmitSellerApplicationRequest;
  path?: never;
  query?: never;
  url: '/api/me/seller-application';
};

export type PostApiMeSellerApplicationErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiMeSellerApplicationError =
  PostApiMeSellerApplicationErrors[keyof PostApiMeSellerApplicationErrors];

export type PostApiMeSellerApplicationResponses = {
  /**
   * OK
   */
  200: SellerApplicationResponse;
};

export type PostApiMeSellerApplicationResponse =
  PostApiMeSellerApplicationResponses[keyof PostApiMeSellerApplicationResponses];

export type GetApiNotificationsSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/notifications/settings';
};

export type GetApiNotificationsSettingsErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type GetApiNotificationsSettingsError =
  GetApiNotificationsSettingsErrors[keyof GetApiNotificationsSettingsErrors];

export type GetApiNotificationsSettingsResponses = {
  /**
   * OK
   */
  200: Array<NotificationSettingResponse>;
};

export type GetApiNotificationsSettingsResponse =
  GetApiNotificationsSettingsResponses[keyof GetApiNotificationsSettingsResponses];

export type PutApiNotificationsSettingsData = {
  body: UpdateNotificationSettingsRequest;
  path?: never;
  query?: never;
  url: '/api/notifications/settings';
};

export type PutApiNotificationsSettingsErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PutApiNotificationsSettingsError =
  PutApiNotificationsSettingsErrors[keyof PutApiNotificationsSettingsErrors];

export type PutApiNotificationsSettingsResponses = {
  /**
   * OK
   */
  200: Array<NotificationSettingResponse>;
};

export type PutApiNotificationsSettingsResponse =
  PutApiNotificationsSettingsResponses[keyof PutApiNotificationsSettingsResponses];

export type GetApiOrdersData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/orders';
};

export type GetApiOrdersResponses = {
  /**
   * OK
   */
  200: PagedResponseOfOrderResponse;
};

export type GetApiOrdersResponse = GetApiOrdersResponses[keyof GetApiOrdersResponses];

export type PostApiOrdersData = {
  body: CreateOrderRequest;
  path?: never;
  query?: never;
  url: '/api/orders';
};

export type PostApiOrdersErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiOrdersError = PostApiOrdersErrors[keyof PostApiOrdersErrors];

export type PostApiOrdersResponses = {
  /**
   * Created
   */
  201: OrderResponse;
};

export type PostApiOrdersResponse = PostApiOrdersResponses[keyof PostApiOrdersResponses];

export type PostApiOrdersByIdCancelData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/orders/{id}/cancel';
};

export type PostApiOrdersByIdCancelErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiOrdersByIdCancelError =
  PostApiOrdersByIdCancelErrors[keyof PostApiOrdersByIdCancelErrors];

export type PostApiOrdersByIdCancelResponses = {
  /**
   * OK
   */
  200: OrderResponse;
};

export type PostApiOrdersByIdCancelResponse =
  PostApiOrdersByIdCancelResponses[keyof PostApiOrdersByIdCancelResponses];

export type GetApiOrdersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/orders/{id}';
};

export type GetApiOrdersByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiOrdersByIdError = GetApiOrdersByIdErrors[keyof GetApiOrdersByIdErrors];

export type GetApiOrdersByIdResponses = {
  /**
   * OK
   */
  200: OrderResponse;
};

export type GetApiOrdersByIdResponse = GetApiOrdersByIdResponses[keyof GetApiOrdersByIdResponses];

export type GetApiPaymentsStripeConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/payments/stripe-config';
};

export type GetApiPaymentsStripeConfigResponses = {
  /**
   * OK
   */
  200: StripePublicConfigResponse;
};

export type GetApiPaymentsStripeConfigResponse =
  GetApiPaymentsStripeConfigResponses[keyof GetApiPaymentsStripeConfigResponses];

export type GetApiSellerBundlesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/seller/bundles';
};

export type GetApiSellerBundlesResponses = {
  /**
   * OK
   */
  200: Array<SellerBundleResponse>;
};

export type GetApiSellerBundlesResponse =
  GetApiSellerBundlesResponses[keyof GetApiSellerBundlesResponses];

export type PostApiSellerBundlesData = {
  body: SaveBundleRequest;
  path?: never;
  query?: never;
  url: '/api/seller/bundles';
};

export type PostApiSellerBundlesErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiSellerBundlesError =
  PostApiSellerBundlesErrors[keyof PostApiSellerBundlesErrors];

export type PostApiSellerBundlesResponses = {
  /**
   * OK
   */
  200: SellerBundleResponse;
};

export type PostApiSellerBundlesResponse =
  PostApiSellerBundlesResponses[keyof PostApiSellerBundlesResponses];

export type GetApiSellerBundlesCandidatesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/seller/bundles/candidates';
};

export type GetApiSellerBundlesCandidatesResponses = {
  /**
   * OK
   */
  200: Array<SellerBundleItemResponse>;
};

export type GetApiSellerBundlesCandidatesResponse =
  GetApiSellerBundlesCandidatesResponses[keyof GetApiSellerBundlesCandidatesResponses];

export type DeleteApiSellerBundlesByBundleIdData = {
  body?: never;
  path: {
    bundleId: string;
  };
  query?: never;
  url: '/api/seller/bundles/{bundleId}';
};

export type DeleteApiSellerBundlesByBundleIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteApiSellerBundlesByBundleIdError =
  DeleteApiSellerBundlesByBundleIdErrors[keyof DeleteApiSellerBundlesByBundleIdErrors];

export type DeleteApiSellerBundlesByBundleIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiSellerBundlesByBundleIdResponse =
  DeleteApiSellerBundlesByBundleIdResponses[keyof DeleteApiSellerBundlesByBundleIdResponses];

export type GetApiSellerBundlesByBundleIdData = {
  body?: never;
  path: {
    bundleId: string;
  };
  query?: never;
  url: '/api/seller/bundles/{bundleId}';
};

export type GetApiSellerBundlesByBundleIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiSellerBundlesByBundleIdError =
  GetApiSellerBundlesByBundleIdErrors[keyof GetApiSellerBundlesByBundleIdErrors];

export type GetApiSellerBundlesByBundleIdResponses = {
  /**
   * OK
   */
  200: SellerBundleResponse;
};

export type GetApiSellerBundlesByBundleIdResponse =
  GetApiSellerBundlesByBundleIdResponses[keyof GetApiSellerBundlesByBundleIdResponses];

export type PutApiSellerBundlesByBundleIdData = {
  body: SaveBundleRequest;
  path: {
    bundleId: string;
  };
  query?: never;
  url: '/api/seller/bundles/{bundleId}';
};

export type PutApiSellerBundlesByBundleIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutApiSellerBundlesByBundleIdError =
  PutApiSellerBundlesByBundleIdErrors[keyof PutApiSellerBundlesByBundleIdErrors];

export type PutApiSellerBundlesByBundleIdResponses = {
  /**
   * OK
   */
  200: SellerBundleResponse;
};

export type PutApiSellerBundlesByBundleIdResponse =
  PutApiSellerBundlesByBundleIdResponses[keyof PutApiSellerBundlesByBundleIdResponses];

export type GetApiSellerDashboardData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/seller/dashboard';
};

export type GetApiSellerDashboardResponses = {
  /**
   * OK
   */
  200: SellerDashboardResponse;
};

export type GetApiSellerDashboardResponse =
  GetApiSellerDashboardResponses[keyof GetApiSellerDashboardResponses];

export type GetApiSellerQnaData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
    unansweredOnly?: boolean;
  };
  url: '/api/seller/qna';
};

export type GetApiSellerQnaResponses = {
  /**
   * OK
   */
  200: PagedResponseOfSellerQnaResponse;
};

export type GetApiSellerQnaResponse = GetApiSellerQnaResponses[keyof GetApiSellerQnaResponses];

export type PostApiSellerQnaByQuestionIdAnswerData = {
  body: AnswerDocumentQuestionRequest;
  path: {
    questionId: string;
  };
  query?: never;
  url: '/api/seller/qna/{questionId}/answer';
};

export type PostApiSellerQnaByQuestionIdAnswerErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiSellerQnaByQuestionIdAnswerError =
  PostApiSellerQnaByQuestionIdAnswerErrors[keyof PostApiSellerQnaByQuestionIdAnswerErrors];

export type PostApiSellerQnaByQuestionIdAnswerResponses = {
  /**
   * OK
   */
  200: SellerQnaResponse;
};

export type PostApiSellerQnaByQuestionIdAnswerResponse =
  PostApiSellerQnaByQuestionIdAnswerResponses[keyof PostApiSellerQnaByQuestionIdAnswerResponses];

export type GetApiSellerStoreSectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/seller/store-sections';
};

export type GetApiSellerStoreSectionsResponses = {
  /**
   * OK
   */
  200: Array<StoreSectionResponse>;
};

export type GetApiSellerStoreSectionsResponse =
  GetApiSellerStoreSectionsResponses[keyof GetApiSellerStoreSectionsResponses];

export type PostApiSellerStoreSectionsData = {
  body: SaveStoreSectionRequest;
  path?: never;
  query?: never;
  url: '/api/seller/store-sections';
};

export type PostApiSellerStoreSectionsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiSellerStoreSectionsError =
  PostApiSellerStoreSectionsErrors[keyof PostApiSellerStoreSectionsErrors];

export type PostApiSellerStoreSectionsResponses = {
  /**
   * OK
   */
  200: StoreSectionResponse;
};

export type PostApiSellerStoreSectionsResponse =
  PostApiSellerStoreSectionsResponses[keyof PostApiSellerStoreSectionsResponses];

export type DeleteApiSellerStoreSectionsBySectionIdData = {
  body?: never;
  path: {
    sectionId: string;
  };
  query?: never;
  url: '/api/seller/store-sections/{sectionId}';
};

export type DeleteApiSellerStoreSectionsBySectionIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiSellerStoreSectionsBySectionIdResponse =
  DeleteApiSellerStoreSectionsBySectionIdResponses[keyof DeleteApiSellerStoreSectionsBySectionIdResponses];

export type PutApiSellerStoreSectionsBySectionIdData = {
  body: SaveStoreSectionRequest;
  path: {
    sectionId: string;
  };
  query?: never;
  url: '/api/seller/store-sections/{sectionId}';
};

export type PutApiSellerStoreSectionsBySectionIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutApiSellerStoreSectionsBySectionIdError =
  PutApiSellerStoreSectionsBySectionIdErrors[keyof PutApiSellerStoreSectionsBySectionIdErrors];

export type PutApiSellerStoreSectionsBySectionIdResponses = {
  /**
   * OK
   */
  200: StoreSectionResponse;
};

export type PutApiSellerStoreSectionsBySectionIdResponse =
  PutApiSellerStoreSectionsBySectionIdResponses[keyof PutApiSellerStoreSectionsBySectionIdResponses];

export type GetApiSellerEarningsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/seller/earnings';
};

export type GetApiSellerEarningsResponses = {
  /**
   * OK
   */
  200: SellerEarningsResponse;
};

export type GetApiSellerEarningsResponse =
  GetApiSellerEarningsResponses[keyof GetApiSellerEarningsResponses];

export type PostApiSellerPayoutsData = {
  body: RequestPayoutRequest;
  path?: never;
  query?: never;
  url: '/api/seller/payouts';
};

export type PostApiSellerPayoutsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiSellerPayoutsError =
  PostApiSellerPayoutsErrors[keyof PostApiSellerPayoutsErrors];

export type PostApiSellerPayoutsResponses = {
  /**
   * OK
   */
  200: PayoutResponse;
};

export type PostApiSellerPayoutsResponse =
  PostApiSellerPayoutsResponses[keyof PostApiSellerPayoutsResponses];

export type GetApiSellerReviewsData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/seller/reviews';
};

export type GetApiSellerReviewsResponses = {
  /**
   * OK
   */
  200: PagedResponseOfSellerReviewResponse;
};

export type GetApiSellerReviewsResponse =
  GetApiSellerReviewsResponses[keyof GetApiSellerReviewsResponses];

export type GetApiSellerDocumentsData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
    Status?: string;
    Search?: string;
  };
  url: '/api/seller/documents';
};

export type GetApiSellerDocumentsResponses = {
  /**
   * OK
   */
  200: PagedResponseOfSellerDocumentSummaryResponse;
};

export type GetApiSellerDocumentsResponse =
  GetApiSellerDocumentsResponses[keyof GetApiSellerDocumentsResponses];

export type PostApiSellerDocumentsData = {
  body: CreateDocumentRequest;
  path?: never;
  query?: never;
  url: '/api/seller/documents';
};

export type PostApiSellerDocumentsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiSellerDocumentsError =
  PostApiSellerDocumentsErrors[keyof PostApiSellerDocumentsErrors];

export type PostApiSellerDocumentsResponses = {
  /**
   * Created
   */
  201: SellerDocumentResponse;
};

export type PostApiSellerDocumentsResponse =
  PostApiSellerDocumentsResponses[keyof PostApiSellerDocumentsResponses];

export type DeleteApiSellerDocumentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/seller/documents/{id}';
};

export type DeleteApiSellerDocumentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type DeleteApiSellerDocumentsByIdError =
  DeleteApiSellerDocumentsByIdErrors[keyof DeleteApiSellerDocumentsByIdErrors];

export type DeleteApiSellerDocumentsByIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiSellerDocumentsByIdResponse =
  DeleteApiSellerDocumentsByIdResponses[keyof DeleteApiSellerDocumentsByIdResponses];

export type GetApiSellerDocumentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/seller/documents/{id}';
};

export type GetApiSellerDocumentsByIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiSellerDocumentsByIdError =
  GetApiSellerDocumentsByIdErrors[keyof GetApiSellerDocumentsByIdErrors];

export type GetApiSellerDocumentsByIdResponses = {
  /**
   * OK
   */
  200: SellerDocumentResponse;
};

export type GetApiSellerDocumentsByIdResponse =
  GetApiSellerDocumentsByIdResponses[keyof GetApiSellerDocumentsByIdResponses];

export type PutApiSellerDocumentsByIdData = {
  body: UpdateDocumentRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/seller/documents/{id}';
};

export type PutApiSellerDocumentsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutApiSellerDocumentsByIdError =
  PutApiSellerDocumentsByIdErrors[keyof PutApiSellerDocumentsByIdErrors];

export type PutApiSellerDocumentsByIdResponses = {
  /**
   * OK
   */
  200: SellerDocumentResponse;
};

export type PutApiSellerDocumentsByIdResponse =
  PutApiSellerDocumentsByIdResponses[keyof PutApiSellerDocumentsByIdResponses];

export type PostApiSellerDocumentsByIdPreviewRasterData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/seller/documents/{id}/preview-raster';
};

export type PostApiSellerDocumentsByIdPreviewRasterErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiSellerDocumentsByIdPreviewRasterError =
  PostApiSellerDocumentsByIdPreviewRasterErrors[keyof PostApiSellerDocumentsByIdPreviewRasterErrors];

export type PostApiSellerDocumentsByIdPreviewRasterResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiSellerDocumentsByIdGeneratePreviewData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/seller/documents/{id}/generate-preview';
};

export type PostApiSellerDocumentsByIdGeneratePreviewErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PostApiSellerDocumentsByIdGeneratePreviewError =
  PostApiSellerDocumentsByIdGeneratePreviewErrors[keyof PostApiSellerDocumentsByIdGeneratePreviewErrors];

export type PostApiSellerDocumentsByIdGeneratePreviewResponses = {
  /**
   * OK
   */
  200: GeneratePreviewResponse;
};

export type PostApiSellerDocumentsByIdGeneratePreviewResponse =
  PostApiSellerDocumentsByIdGeneratePreviewResponses[keyof PostApiSellerDocumentsByIdGeneratePreviewResponses];

export type GetApiSellerDocumentsByIdMainFilesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/seller/documents/{id}/main-files';
};

export type GetApiSellerDocumentsByIdMainFilesErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiSellerDocumentsByIdMainFilesError =
  GetApiSellerDocumentsByIdMainFilesErrors[keyof GetApiSellerDocumentsByIdMainFilesErrors];

export type GetApiSellerDocumentsByIdMainFilesResponses = {
  /**
   * OK
   */
  200: Array<SellerDocumentMainFileResponse>;
};

export type GetApiSellerDocumentsByIdMainFilesResponse =
  GetApiSellerDocumentsByIdMainFilesResponses[keyof GetApiSellerDocumentsByIdMainFilesResponses];

export type PostApiSellerDocumentsByIdMainFilesData = {
  body: AddSellerDocumentMainFileRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/seller/documents/{id}/main-files';
};

export type PostApiSellerDocumentsByIdMainFilesErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type PostApiSellerDocumentsByIdMainFilesError =
  PostApiSellerDocumentsByIdMainFilesErrors[keyof PostApiSellerDocumentsByIdMainFilesErrors];

export type PostApiSellerDocumentsByIdMainFilesResponses = {
  /**
   * Created
   */
  201: SellerDocumentMainFileResponse;
};

export type PostApiSellerDocumentsByIdMainFilesResponse =
  PostApiSellerDocumentsByIdMainFilesResponses[keyof PostApiSellerDocumentsByIdMainFilesResponses];

export type PutApiSellerDocumentsByIdListedMainFileData = {
  body: SetListedSellerDocumentMainFileRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/seller/documents/{id}/listed-main-file';
};

export type PutApiSellerDocumentsByIdListedMainFileErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type PutApiSellerDocumentsByIdListedMainFileError =
  PutApiSellerDocumentsByIdListedMainFileErrors[keyof PutApiSellerDocumentsByIdListedMainFileErrors];

export type PutApiSellerDocumentsByIdListedMainFileResponses = {
  /**
   * OK
   */
  200: SellerDocumentResponse;
};

export type PutApiSellerDocumentsByIdListedMainFileResponse =
  PutApiSellerDocumentsByIdListedMainFileResponses[keyof PutApiSellerDocumentsByIdListedMainFileResponses];

export type GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlData = {
  body?: never;
  path: {
    id: string;
    fileId: string;
  };
  query?: {
    expiresSeconds?: number;
  };
  url: '/api/seller/documents/{id}/main-files/{fileId}/download-url';
};

export type GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Not Implemented
   */
  501: unknown;
};

export type GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlError =
  GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlErrors[keyof GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlErrors];

export type GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlResponses = {
  /**
   * OK
   */
  200: PresignedUrlResponse;
};

export type GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlResponse =
  GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlResponses[keyof GetApiSellerDocumentsByIdMainFilesByFileIdDownloadUrlResponses];

export type GetApiSellerDocumentsByIdDownloadUrlData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    expiresSeconds?: number;
  };
  url: '/api/seller/documents/{id}/download-url';
};

export type GetApiSellerDocumentsByIdDownloadUrlErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Not Implemented
   */
  501: unknown;
};

export type GetApiSellerDocumentsByIdDownloadUrlError =
  GetApiSellerDocumentsByIdDownloadUrlErrors[keyof GetApiSellerDocumentsByIdDownloadUrlErrors];

export type GetApiSellerDocumentsByIdDownloadUrlResponses = {
  /**
   * OK
   */
  200: PresignedUrlResponse;
};

export type GetApiSellerDocumentsByIdDownloadUrlResponse =
  GetApiSellerDocumentsByIdDownloadUrlResponses[keyof GetApiSellerDocumentsByIdDownloadUrlResponses];

export type GetApiSellersBySellerIdProfileData = {
  body?: never;
  path: {
    sellerId: string;
  };
  query?: never;
  url: '/api/sellers/{sellerId}/profile';
};

export type GetApiSellersBySellerIdProfileErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiSellersBySellerIdProfileError =
  GetApiSellersBySellerIdProfileErrors[keyof GetApiSellersBySellerIdProfileErrors];

export type GetApiSellersBySellerIdProfileResponses = {
  /**
   * OK
   */
  200: SellerProfileResponse;
};

export type GetApiSellersBySellerIdProfileResponse =
  GetApiSellersBySellerIdProfileResponses[keyof GetApiSellersBySellerIdProfileResponses];

export type DeleteApiSellersBySellerIdFollowData = {
  body?: never;
  path: {
    sellerId: string;
  };
  query?: never;
  url: '/api/sellers/{sellerId}/follow';
};

export type DeleteApiSellersBySellerIdFollowErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type DeleteApiSellersBySellerIdFollowError =
  DeleteApiSellersBySellerIdFollowErrors[keyof DeleteApiSellersBySellerIdFollowErrors];

export type DeleteApiSellersBySellerIdFollowResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiSellersBySellerIdFollowResponse =
  DeleteApiSellersBySellerIdFollowResponses[keyof DeleteApiSellersBySellerIdFollowResponses];

export type GetApiSellersBySellerIdFollowData = {
  body?: never;
  path: {
    sellerId: string;
  };
  query?: never;
  url: '/api/sellers/{sellerId}/follow';
};

export type GetApiSellersBySellerIdFollowErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type GetApiSellersBySellerIdFollowError =
  GetApiSellersBySellerIdFollowErrors[keyof GetApiSellersBySellerIdFollowErrors];

export type GetApiSellersBySellerIdFollowResponses = {
  /**
   * OK
   */
  200: SellerFollowStatusResponse;
};

export type GetApiSellersBySellerIdFollowResponse =
  GetApiSellersBySellerIdFollowResponses[keyof GetApiSellersBySellerIdFollowResponses];

export type PostApiSellersBySellerIdFollowData = {
  body?: never;
  path: {
    sellerId: string;
  };
  query?: never;
  url: '/api/sellers/{sellerId}/follow';
};

export type PostApiSellersBySellerIdFollowErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiSellersBySellerIdFollowError =
  PostApiSellersBySellerIdFollowErrors[keyof PostApiSellersBySellerIdFollowErrors];

export type PostApiSellersBySellerIdFollowResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiWebhooksStripeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/webhooks/stripe';
};

export type PostApiWebhooksStripeResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiSystemStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/system/status';
};

export type GetApiSystemStatusResponses = {
  /**
   * OK
   */
  200: SystemStatusResponse;
};

export type GetApiSystemStatusResponse =
  GetApiSystemStatusResponses[keyof GetApiSystemStatusResponses];

export type GetApiSystemR2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/system/r2';
};

export type GetApiSystemR2Responses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiSystemTestEmailData = {
  body: TestEmailRequest;
  path?: never;
  query?: never;
  url: '/api/system/test-email';
};

export type PostApiSystemTestEmailErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiSystemTestEmailError =
  PostApiSystemTestEmailErrors[keyof PostApiSystemTestEmailErrors];

export type PostApiSystemTestEmailResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiWishlistData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/wishlist';
};

export type DeleteApiWishlistResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiWishlistResponse =
  DeleteApiWishlistResponses[keyof DeleteApiWishlistResponses];

export type GetApiWishlistData = {
  body?: never;
  path?: never;
  query?: {
    Page?: number;
    PageSize?: number;
  };
  url: '/api/wishlist';
};

export type GetApiWishlistResponses = {
  /**
   * OK
   */
  200: PagedResponseOfWishlistItemResponse;
};

export type GetApiWishlistResponse = GetApiWishlistResponses[keyof GetApiWishlistResponses];

export type PostApiWishlistData = {
  body: AddToWishlistRequest;
  path?: never;
  query?: never;
  url: '/api/wishlist';
};

export type PostApiWishlistErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
};

export type PostApiWishlistError = PostApiWishlistErrors[keyof PostApiWishlistErrors];

export type PostApiWishlistResponses = {
  /**
   * Created
   */
  201: WishlistItemResponse;
};

export type PostApiWishlistResponse = PostApiWishlistResponses[keyof PostApiWishlistResponses];

export type DeleteApiWishlistByDocumentIdData = {
  body?: never;
  path: {
    documentId: string;
  };
  query?: never;
  url: '/api/wishlist/{documentId}';
};

export type DeleteApiWishlistByDocumentIdResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteApiWishlistByDocumentIdResponse =
  DeleteApiWishlistByDocumentIdResponses[keyof DeleteApiWishlistByDocumentIdResponses];
