import { signal } from '@angular/core';
import { TestBed } from '@angular/core/testing';
import { NzMessageService } from 'ng-zorro-antd/message';
import { AdminApprovalPage } from './approval.page';
import { AdminService } from '../../../core/services';
import { mapAdminPendingToDocumentItem } from '../../../core/api-mappers/mappers';
import { errorActionState, idleActionState, loadingActionState, type ActionState } from '../../../core/services/action-state';
import type { DocumentItem } from '../../../core/models';
import type { AdminPendingDocumentResponse } from '../../../core/api/types.gen';

/**
 * ai-approval-prescreen v1 §1/§4/AC-7 test list — admin approval queue AI prescreen UI:
 *  - renders the risk-level badge (Safe/Warning/HighRisk) and the "ยังไม่ได้ประเมิน" fallback
 *  - renders `aiPrescreenFlags` as a list of flag pills
 *  - renders the "AI สร้าง" / "รายการนี้สร้างขึ้นโดยระบบ" badge when `isAutoGenerated=true`
 *  - clicking "วิเคราะห์ใหม่" calls `admin.prescreenDocument(id)` and refreshes the list
 *
 * This is the first spec for `approval.page.ts` — the page previously had no test coverage at
 * all (§0.2 AC-7 required-fix, not gate-blocking but required before the final close).
 */
function buildDoc(over: Partial<AdminPendingDocumentResponse> = {}): DocumentItem {
  return mapAdminPendingToDocumentItem({
    id: 'doc-1',
    title: 'แบบฝึกหัดคณิตศาสตร์ ป.4',
    shortDescription: 'โจทย์เศษส่วนพร้อมเฉลย',
    coverUrl: null,
    sellerName: 'ครูเอ',
    categoryIds: ['cat-math'],
    format: 'pdf',
    price: 49,
    submittedAt: '2026-09-01T00:00:00Z',
    ...over,
  });
}

function buildAdmin(docs: DocumentItem[], total: number | null = null) {
  const pendingDocuments = signal<DocumentItem[]>(docs);
  const pendingTotal = signal<number | null>(total);
  const pendingState = signal<ActionState>(idleActionState());
  return {
    pendingDocuments: pendingDocuments.asReadonly(),
    pendingTotal: pendingTotal.asReadonly(),
    _pendingTotalSignal: pendingTotal,
    pendingHasMore: signal(false).asReadonly(),
    pendingState: pendingState.asReadonly(),
    _pendingStateSignal: pendingState,
    refreshPendingDocuments: vi.fn(async () => {}),
    loadMorePendingDocuments: vi.fn(async () => {}),
    fetchAdminDocumentDetail: vi.fn(async () => null),
    prescreenDocument: vi.fn(async () => {
      // Mirrors the real AdminService: a successful prescreen refreshes the pending queue so the
      // new risk badge/flags show up without a manual reload.
    }),
    approveDocument: vi.fn(async () => {}),
    rejectDocument: vi.fn(async () => {}),
    getFileDownloadUrl: vi.fn(async () => null),
    _pendingDocumentsSignal: pendingDocuments,
  };
}

async function settle(): Promise<void> {
  for (let i = 0; i < 6; i++) {
    await new Promise((resolve) => setTimeout(resolve, 0));
  }
}

function render(admin: ReturnType<typeof buildAdmin>) {
  const messages = { success: vi.fn(), warning: vi.fn(), error: vi.fn(), info: vi.fn() };

  TestBed.configureTestingModule({
    imports: [AdminApprovalPage],
    providers: [
      { provide: AdminService, useValue: admin },
      { provide: NzMessageService, useValue: messages },
    ],
  });

  const fixture = TestBed.createComponent(AdminApprovalPage);
  fixture.detectChanges();
  return { fixture, messages };
}

afterEach(() => TestBed.resetTestingModule());

describe('AdminApprovalPage — AI prescreen (ai-approval-prescreen v1 §1/AC-7)', () => {
  it('shows "ยังไม่ได้ประเมิน" when aiPrescreenRiskLevel is null', async () => {
    const admin = buildAdmin([buildDoc({ aiPrescreenRiskLevel: null })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).toContain('ยังไม่ได้ประเมิน');
  });

  it.each([
    ['Safe', 'เสี่ยงต่ำ / ผ่านเกณฑ์'],
    ['Warning', 'ควรตรวจสอบเพิ่มเติม'],
    ['HighRisk', 'พบความเสี่ยงสูง'],
  ])('renders the %s risk-level badge in the detail panel', async (riskLevel, expectedCopy) => {
    const admin = buildAdmin([buildDoc({ aiPrescreenRiskLevel: riskLevel })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).toContain(expectedCopy);
  });

  it('renders each aiPrescreenFlags entry as a flag pill', async () => {
    const admin = buildAdmin([
      buildDoc({ aiPrescreenRiskLevel: 'HighRisk', aiPrescreenFlags: ['empty_or_short', 'copyright_suspicion'] }),
    ]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).toContain('empty_or_short');
    expect(text).toContain('copyright_suspicion');
  });

  it('renders the "สร้างขึ้นโดยระบบ" badge when isAutoGenerated=true', async () => {
    const admin = buildAdmin([buildDoc({ isAutoGenerated: true })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).toContain('รายการนี้สร้างขึ้นโดยระบบ');
  });

  it('does not render the auto-generated badge when isAutoGenerated is false/undefined', async () => {
    const admin = buildAdmin([buildDoc({ isAutoGenerated: false })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).not.toContain('รายการนี้สร้างขึ้นโดยระบบ');
  });

  it('clicking "วิเคราะห์ใหม่" calls admin.prescreenDocument(id) and shows the success toast', async () => {
    const admin = buildAdmin([buildDoc({ id: 'doc-9', aiPrescreenRiskLevel: null })]);
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.runPrescreen('doc-9');

    expect(admin.prescreenDocument).toHaveBeenCalledWith('doc-9');
    expect(messages.success).toHaveBeenCalledWith('ประเมินความเสี่ยงด้วย AI เรียบร้อย');
  });

  it('shows the error toast when prescreenDocument rejects', async () => {
    const admin = buildAdmin([buildDoc({ id: 'doc-9' })]);
    admin.prescreenDocument.mockRejectedValueOnce(new Error('AI unavailable'));
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.runPrescreen('doc-9');

    expect(messages.error).toHaveBeenCalledWith('ประเมินความเสี่ยงด้วย AI ไม่สำเร็จ');
  });
});


/**
 * Popup-free file delivery on the approval queue.
 *
 * Every one of these four handlers used to be `const win = window.open('', '_blank')` followed
 * by `win.location.href = url`, wrapped in `catch { win?.close(); }`. A blocked popup
 * (`window.open` → `null`) therefore produced *nothing at all*: no tab, no file, and — because
 * the catch swallowed everything — no message either. Reproduced live on /admin/approval.
 */
describe('AdminApprovalPage — file download/open without popups', () => {
  const MSG_FAILED = 'ดาวน์โหลดไฟล์ไม่สำเร็จ — ไฟล์อาจถูกลบออกจากระบบจัดเก็บแล้ว';
  const MSG_BLOCKED = 'เบราว์เซอร์บล็อกการเปิดแท็บใหม่ ระบบจึงบันทึกไฟล์ให้แทน';

  let realFetch: typeof globalThis.fetch;
  let realOpen: typeof window.open;
  let realCreateObjectURL: typeof URL.createObjectURL;
  let realRevokeObjectURL: typeof URL.revokeObjectURL;
  let realCreateElement: typeof document.createElement;
  let fetchMock: ReturnType<typeof vi.fn>;
  let openMock: ReturnType<typeof vi.fn>;
  let saved: HTMLAnchorElement[];

  function fileResponse(ok = true): Response {
    return {
      ok,
      status: ok ? 200 : 404,
      headers: new Headers(),
      blob: async () => new Blob(['bytes'], { type: 'application/pdf' }),
    } as unknown as Response;
  }

  beforeEach(() => {
    realFetch = globalThis.fetch;
    fetchMock = vi.fn(async () => fileResponse());
    globalThis.fetch = fetchMock as unknown as typeof globalThis.fetch;

    realOpen = window.open;
    openMock = vi.fn(() => null);
    window.open = openMock as unknown as typeof window.open;

    realCreateObjectURL = URL.createObjectURL;
    realRevokeObjectURL = URL.revokeObjectURL;
    URL.createObjectURL = vi.fn(() => 'blob:mock/admin') as unknown as typeof URL.createObjectURL;
    URL.revokeObjectURL = vi.fn() as unknown as typeof URL.revokeObjectURL;

    saved = [];
    realCreateElement = document.createElement.bind(document);
    vi.spyOn(document, 'createElement').mockImplementation(((tag: string) => {
      const el = realCreateElement(tag);
      if (tag === 'a') {
        const anchor = el as HTMLAnchorElement;
        anchor.click = () => {
          saved.push(anchor);
        };
      }
      return el;
    }) as typeof document.createElement);
  });

  afterEach(() => {
    globalThis.fetch = realFetch;
    window.open = realOpen;
    URL.createObjectURL = realCreateObjectURL;
    URL.revokeObjectURL = realRevokeObjectURL;
    vi.restoreAllMocks();
  });

  it('downloadMainFile() saves the file through an anchor and never opens a popup', async () => {
    const admin = buildAdmin([buildDoc()]);
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.downloadMainFile('orig/main.pdf');

    expect(admin.getFileDownloadUrl).toHaveBeenCalledWith('orig/main.pdf', false);
    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect((fetchMock.mock.calls[0] as [string])[0]).toContain('orig/main.pdf');
    expect(saved).toHaveLength(1);
    expect(openMock).not.toHaveBeenCalled();
    expect(messages.error).not.toHaveBeenCalled();
  });

  it('downloadMainFile() reports the failure instead of swallowing it (404 from storage)', async () => {
    fetchMock.mockResolvedValue(fileResponse(false));
    const admin = buildAdmin([buildDoc()]);
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.downloadMainFile('orig/gone.pdf');

    expect(saved).toHaveLength(0);
    expect(messages.error).toHaveBeenCalledWith(MSG_FAILED);
  });

  it('downloadMainFile() reports the failure when the network itself fails', async () => {
    fetchMock.mockRejectedValue(new TypeError('network down'));
    const admin = buildAdmin([buildDoc()]);
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.downloadMainFile('orig/main.pdf');

    expect(messages.error).toHaveBeenCalledWith(MSG_FAILED);
  });

  it('downloadSaleFile() goes through the same path for the sale file key', async () => {
    const admin = buildAdmin([buildDoc()]);
    const { fixture, messages } = render(admin);
    await settle();
    fixture.componentInstance.previewDetail.set({
      fileStorageKey: 'sale/file.pdf',
    } as unknown as NonNullable<ReturnType<typeof fixture.componentInstance.previewDetail>>);

    await fixture.componentInstance.downloadSaleFile();

    expect(admin.getFileDownloadUrl).toHaveBeenCalledWith('sale/file.pdf', false);
    expect(saved).toHaveLength(1);
    expect(messages.error).not.toHaveBeenCalled();
  });

  it('openMainFile() opens the blob in a tab when the popup is allowed', async () => {
    openMock.mockReturnValue({} as Window);
    const admin = buildAdmin([buildDoc()]);
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.openMainFile('orig/main.pdf');

    expect(admin.getFileDownloadUrl).toHaveBeenCalledWith('orig/main.pdf', true);
    expect(openMock).toHaveBeenCalledWith('blob:mock/admin', '_blank');
    expect(saved).toHaveLength(0);
    expect(messages.error).not.toHaveBeenCalled();
  });

  it('openMainFile() falls back to saving the file when the popup is blocked, and says so', async () => {
    openMock.mockReturnValue(null);
    const admin = buildAdmin([buildDoc()]);
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.openMainFile('orig/main.pdf');

    expect(saved).toHaveLength(1);
    expect(messages.info).toHaveBeenCalledWith(MSG_BLOCKED);
    expect(messages.error).not.toHaveBeenCalled();
  });

  it('openMainFile() reports a real failure', async () => {
    fetchMock.mockResolvedValue(fileResponse(false));
    const admin = buildAdmin([buildDoc()]);
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.openMainFile('orig/gone.pdf');

    expect(messages.error).toHaveBeenCalledWith(MSG_FAILED);
  });
});

describe('AdminApprovalPage — responsive master-detail (responsive-ui v1 U4-3)', () => {
  function el(fixture: { nativeElement: unknown }, testId: string): HTMLElement {
    return (fixture.nativeElement as HTMLElement).querySelector(`[data-testid="${testId}"]`) as HTMLElement;
  }

  it('starts on the list view below 1024px (detail column hidden there, both shown at lg)', async () => {
    const { fixture } = render(buildAdmin([buildDoc()]));
    await settle();
    fixture.detectChanges();

    expect(fixture.componentInstance.detailOpen()).toBe(false);
    expect(el(fixture, 'approval-list').className).not.toContain('max-lg:hidden');
    expect(el(fixture, 'approval-detail').className).toContain('max-lg:hidden');
    expect((fixture.nativeElement as HTMLElement).querySelector('app-sticky-action-bar')).toBeNull();
  });

  it('selecting a row switches to the full-width detail view with a back button', async () => {
    const admin = buildAdmin([buildDoc({ id: 'doc-1' }), buildDoc({ id: 'doc-2', title: 'เอกสารที่สอง' })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const rows = el(fixture, 'approval-list').querySelectorAll('button.card-soft');
    (rows[1] as HTMLButtonElement).click();
    fixture.detectChanges();

    expect(fixture.componentInstance.detailOpen()).toBe(true);
    expect(fixture.componentInstance.selected()?.id).toBe('doc-2');
    expect(el(fixture, 'approval-list').className).toContain('max-lg:hidden');
    expect(el(fixture, 'approval-detail').className).not.toContain('max-lg:hidden');

    el(fixture, 'approval-back').click();
    fixture.detectChanges();
    expect(fixture.componentInstance.detailOpen()).toBe(false);
    expect(el(fixture, 'approval-list').className).not.toContain('max-lg:hidden');
  });

  it('puts approve / reject in a phone sticky action bar while the detail view is open', async () => {
    const admin = buildAdmin([buildDoc({ id: 'doc-1' })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    fixture.componentInstance.openDetail('doc-1');
    fixture.detectChanges();

    const sticky = el(fixture, 'approval-actions-sticky');
    expect(sticky).not.toBeNull();
    expect(sticky.closest('app-sticky-action-bar')).not.toBeNull();
    const buttons = sticky.querySelectorAll('button');
    expect(buttons.length).toBe(2);

    (buttons[1] as HTMLButtonElement).click();
    await settle();
    fixture.detectChanges();

    expect(admin.approveDocument).toHaveBeenCalledWith('doc-1');
    // back to the list once the document leaves the queue
    expect(fixture.componentInstance.detailOpen()).toBe(false);
  });

  it('keeps the inline approve / reject buttons for >=744', async () => {
    const { fixture } = render(buildAdmin([buildDoc()]));
    await settle();
    fixture.detectChanges();

    const inline = el(fixture, 'approval-actions-inline');
    expect(inline.className).toContain('md:grid');
    expect(inline.querySelectorAll('button').length).toBe(2);
  });

  it('header count shows the server total of the queue, not the loaded rows (F87)', async () => {
    const admin = buildAdmin([buildDoc({ id: 'doc-1' }), buildDoc({ id: 'doc-2' })], 1234);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();
    expect(el(fixture, 'approval-total').textContent?.trim()).toBe('1234');

    admin._pendingTotalSignal.set(null);
    fixture.detectChanges();
    expect(el(fixture, 'approval-total').textContent?.trim()).toBe('2');
  });

  it('back from the <1024 detail view returns the list to the offset it was left at (F138)', async () => {
    const admin = buildAdmin([buildDoc({ id: 'doc-1' }), buildDoc({ id: 'doc-2' })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const scrollTo = vi.spyOn(window, 'scrollTo').mockImplementation(() => {});
    const scrollY = vi.spyOn(window, 'scrollY', 'get').mockReturnValue(640);
    const width = vi.spyOn(window, 'innerWidth', 'get').mockReturnValue(390);
    try {
      fixture.componentInstance.openDetail('doc-2');
      fixture.detectChanges();
      expect(scrollTo).toHaveBeenLastCalledWith({ top: 0, behavior: 'instant' });

      el(fixture, 'approval-back').click();
      fixture.detectChanges();
      await fixture.whenStable();
      expect(scrollTo).toHaveBeenLastCalledWith({ top: 640, behavior: 'instant' });
    } finally {
      scrollTo.mockRestore();
      scrollY.mockRestore();
      width.mockRestore();
    }
  });

  it('does not move the page when a row is picked at >=1024 (both columns stay)', async () => {
    const { fixture } = render(buildAdmin([buildDoc({ id: 'doc-1' })]));
    await settle();
    fixture.detectChanges();
    const scrollTo = vi.spyOn(window, 'scrollTo').mockImplementation(() => {});
    const width = vi.spyOn(window, 'innerWidth', 'get').mockReturnValue(1280);
    try {
      fixture.componentInstance.openDetail('doc-1');
      expect(scrollTo).not.toHaveBeenCalled();
    } finally {
      scrollTo.mockRestore();
      width.mockRestore();
    }
  });

  it('counts only the sheet filters (seller name + dates) and clears them', () => {
    const { fixture } = render(buildAdmin([buildDoc()]));
    const page = fixture.componentInstance;
    page.titleQuery.set('คณิต');
    page.sellerNameQuery.set('ครูเอ');
    page.postedFrom.set('2026-09-01');
    expect(page.activeFilterCount()).toBe(2);

    page.clearFilters();
    expect(page.activeFilterCount()).toBe(0);
    expect(page.titleQuery()).toBe('คณิต');
  });
});

describe('AdminApprovalPage — data states (responsive-ui v1.4 R-17, G-27)', () => {
  function el(fixture: { nativeElement: unknown }, testId: string): HTMLElement | null {
    return (fixture.nativeElement as HTMLElement).querySelector(`[data-testid="${testId}"]`);
  }

  it('shows a skeleton — not "ไม่มีเอกสารรออนุมัติ" — before the first queue answer', async () => {
    const admin = buildAdmin([], null);
    admin._pendingStateSignal.set(loadingActionState());
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    expect(fixture.componentInstance.listState()).toBe('loading');
    expect(el(fixture, 'approval-loading')?.getAttribute('aria-busy')).toBe('true');
    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).not.toContain('ไม่มีเอกสารรออนุมัติ');
    expect(text).not.toContain('เลือกเอกสารที่ต้องการตรวจสอบ');
    expect(el(fixture, 'approval-total')?.textContent?.trim()).toBe('—');
  });

  it('treats idle with an unknown total (search not answered yet) as loading', () => {
    const { fixture } = render(buildAdmin([], null));
    expect(fixture.componentInstance.listState()).toBe('loading');
  });

  it('shows a message and a common.retry that re-runs the search with the current filters on failure', async () => {
    const admin = buildAdmin([], null);
    admin._pendingStateSignal.set(errorActionState('โหลดไม่สำเร็จ'));
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();
    fixture.componentInstance.titleQuery.set('คณิต');

    expect(fixture.componentInstance.listState()).toBe('error');
    const error = el(fixture, 'approval-error');
    expect(error?.getAttribute('role')).toBe('alert');
    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).not.toContain('ไม่มีเอกสารรออนุมัติ');
    expect(text).not.toContain('เลือกเอกสารที่ต้องการตรวจสอบ');
    expect(el(fixture, 'approval-total')?.textContent?.trim()).toBe('—');

    admin.refreshPendingDocuments.mockClear();
    const retry = el(fixture, 'approval-retry') as HTMLButtonElement;
    expect(retry.textContent?.trim()).toBe('ลองใหม่อีกครั้ง');
    expect(retry.classList).toContain('btn-pink');
    retry.click();
    expect(admin.refreshPendingDocuments).toHaveBeenCalledWith(expect.objectContaining({ title: 'คณิต' }));
  });

  it('shows the "ไม่มีเอกสารรออนุมัติ" empty state only for a queue that answered with zero rows', async () => {
    const { fixture } = render(buildAdmin([], 0));
    await settle();
    fixture.detectChanges();

    expect(fixture.componentInstance.listState()).toBe('empty');
    expect((fixture.nativeElement as HTMLElement).textContent).toContain('ไม่มีเอกสารรออนุมัติ');
    expect(el(fixture, 'approval-loading')).toBeNull();
    expect(el(fixture, 'approval-error')).toBeNull();
    expect(el(fixture, 'approval-total')?.textContent?.trim()).toBe('0');
  });

  it('searches once on entry — the queue flipping its own load state does not re-run the search', async () => {
    const admin = buildAdmin([], null);
    admin.refreshPendingDocuments.mockImplementation(async () => {
      // Like the real pager: reads its own state synchronously, then flips it around the request.
      admin.pendingState();
      admin._pendingStateSignal.set(loadingActionState());
      await Promise.resolve();
      admin._pendingStateSignal.set(errorActionState('โหลดไม่สำเร็จ'));
    });
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();
    await new Promise((resolve) => setTimeout(resolve, 450)); // past the 400ms filter debounce
    fixture.detectChanges();
    await settle();

    expect(admin.refreshPendingDocuments).toHaveBeenCalledTimes(1);
    expect(fixture.componentInstance.listState()).toBe('error');
  });

  it('keeps the loaded rows on screen while a refresh is in flight', async () => {
    const admin = buildAdmin([buildDoc()], 1);
    admin._pendingStateSignal.set(loadingActionState());
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();
    expect(fixture.componentInstance.listState()).toBe('data');
    expect(el(fixture, 'approval-list')?.querySelectorAll('button.card-soft').length).toBe(1);
  });
});

describe('AdminApprovalPage — reject modal actions (responsive-ui v1.4 R-2, G2-8)', () => {
  afterEach(() => TestBed.resetTestingModule());

  it('stacks cancel / confirm below 744 and gives the confirm button a 44px coarse-pointer height', async () => {
    const { fixture } = render(buildAdmin([buildDoc({ id: 'doc-1', title: 'เอกสาร A' })]));
    await settle();
    fixture.componentInstance.reject('doc-1', 'เอกสาร A');
    fixture.detectChanges();
    await settle();
    fixture.detectChanges();

    const actions = document.querySelector('[data-testid="reject-modal-actions"]') as HTMLElement | null;
    expect(actions).not.toBeNull();
    expect(actions!.className).toContain('flex-col');
    expect(actions!.className).toContain('md:flex-row');
    const confirm = document.querySelector('[data-testid="reject-modal-confirm"]') as HTMLButtonElement;
    expect(confirm.className).toContain('[@media(pointer:coarse)]:min-h-11');
    expect(confirm.className).toContain('justify-center');
    // the cancel button is a .btn-ghost, which the global touch rule already makes 44px
    expect(actions!.querySelector('button')?.classList).toContain('btn-ghost');
  });
});
