import { signal } from '@angular/core';
import { TestBed } from '@angular/core/testing';
import { NzMessageService } from 'ng-zorro-antd/message';
import { AdminApprovalPage } from './approval.page';
import { AdminService } from '../../../core/services';
import { mapAdminPendingToDocumentItem } from '../../../core/api-mappers/mappers';
import { idleActionState } from '../../../core/services/action-state';
import type { DocumentItem } from '../../../core/models';
import type { AdminPendingDocumentResponse } from '../../../core/api/types.gen';

/**
 * ai-approval-prescreen v1 §1/§4/AC-7 test list — admin approval queue AI prescreen UI:
 *  - renders the risk-level badge (Safe/Warning/HighRisk) and the "ยังไม่ได้ประเมิน" fallback
 *  - renders `aiPrescreenFlags` as a list of flag pills
 *  - renders the "AI สร้าง" / "รายการนี้สร้างขึ้นโดยระบบ" badge when `isAutoGenerated=true`
 *  - clicking "วิเคราะห์ใหม่" calls `admin.prescreenDocument(id)` and refreshes the list
 *
 * This is the first spec for `approval.page.ts` — the page previously had no test coverage at
 * all (§0.2 AC-7 required-fix, not gate-blocking but required before the final close).
 */
function buildDoc(over: Partial<AdminPendingDocumentResponse> = {}): DocumentItem {
  return mapAdminPendingToDocumentItem({
    id: 'doc-1',
    title: 'แบบฝึกหัดคณิตศาสตร์ ป.4',
    shortDescription: 'โจทย์เศษส่วนพร้อมเฉลย',
    coverUrl: null,
    sellerName: 'ครูเอ',
    categoryIds: ['cat-math'],
    format: 'pdf',
    price: 49,
    submittedAt: '2026-09-01T00:00:00Z',
    ...over,
  });
}

function buildAdmin(docs: DocumentItem[]) {
  const pendingDocuments = signal<DocumentItem[]>(docs);
  return {
    pendingDocuments: pendingDocuments.asReadonly(),
    pendingHasMore: signal(false).asReadonly(),
    pendingState: signal(idleActionState()).asReadonly(),
    refreshPendingDocuments: vi.fn(async () => {}),
    loadMorePendingDocuments: vi.fn(async () => {}),
    fetchAdminDocumentDetail: vi.fn(async () => null),
    prescreenDocument: vi.fn(async () => {
      // Mirrors the real AdminService: a successful prescreen refreshes the pending queue so the
      // new risk badge/flags show up without a manual reload.
    }),
    approveDocument: vi.fn(async () => {}),
    rejectDocument: vi.fn(async () => {}),
    getFileDownloadUrl: vi.fn(async () => null),
    _pendingDocumentsSignal: pendingDocuments,
  };
}

async function settle(): Promise<void> {
  for (let i = 0; i < 6; i++) {
    await new Promise((resolve) => setTimeout(resolve, 0));
  }
}

function render(admin: ReturnType<typeof buildAdmin>) {
  const messages = { success: vi.fn(), warning: vi.fn(), error: vi.fn() };

  TestBed.configureTestingModule({
    imports: [AdminApprovalPage],
    providers: [
      { provide: AdminService, useValue: admin },
      { provide: NzMessageService, useValue: messages },
    ],
  });

  const fixture = TestBed.createComponent(AdminApprovalPage);
  fixture.detectChanges();
  return { fixture, messages };
}

afterEach(() => TestBed.resetTestingModule());

describe('AdminApprovalPage — AI prescreen (ai-approval-prescreen v1 §1/AC-7)', () => {
  it('shows "ยังไม่ได้ประเมิน" when aiPrescreenRiskLevel is null', async () => {
    const admin = buildAdmin([buildDoc({ aiPrescreenRiskLevel: null })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).toContain('ยังไม่ได้ประเมิน');
  });

  it.each([
    ['Safe', 'เสี่ยงต่ำ / ผ่านเกณฑ์'],
    ['Warning', 'ควรตรวจสอบเพิ่มเติม'],
    ['HighRisk', 'พบความเสี่ยงสูง'],
  ])('renders the %s risk-level badge in the detail panel', async (riskLevel, expectedCopy) => {
    const admin = buildAdmin([buildDoc({ aiPrescreenRiskLevel: riskLevel })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).toContain(expectedCopy);
  });

  it('renders each aiPrescreenFlags entry as a flag pill', async () => {
    const admin = buildAdmin([
      buildDoc({ aiPrescreenRiskLevel: 'HighRisk', aiPrescreenFlags: ['empty_or_short', 'copyright_suspicion'] }),
    ]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).toContain('empty_or_short');
    expect(text).toContain('copyright_suspicion');
  });

  it('renders the "สร้างขึ้นโดยระบบ" badge when isAutoGenerated=true', async () => {
    const admin = buildAdmin([buildDoc({ isAutoGenerated: true })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).toContain('รายการนี้สร้างขึ้นโดยระบบ');
  });

  it('does not render the auto-generated badge when isAutoGenerated is false/undefined', async () => {
    const admin = buildAdmin([buildDoc({ isAutoGenerated: false })]);
    const { fixture } = render(admin);
    await settle();
    fixture.detectChanges();

    const text = (fixture.nativeElement as HTMLElement).textContent ?? '';
    expect(text).not.toContain('รายการนี้สร้างขึ้นโดยระบบ');
  });

  it('clicking "วิเคราะห์ใหม่" calls admin.prescreenDocument(id) and shows the success toast', async () => {
    const admin = buildAdmin([buildDoc({ id: 'doc-9', aiPrescreenRiskLevel: null })]);
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.runPrescreen('doc-9');

    expect(admin.prescreenDocument).toHaveBeenCalledWith('doc-9');
    expect(messages.success).toHaveBeenCalledWith('ประเมินความเสี่ยงด้วย AI เรียบร้อย');
  });

  it('shows the error toast when prescreenDocument rejects', async () => {
    const admin = buildAdmin([buildDoc({ id: 'doc-9' })]);
    admin.prescreenDocument.mockRejectedValueOnce(new Error('AI unavailable'));
    const { fixture, messages } = render(admin);
    await settle();

    await fixture.componentInstance.runPrescreen('doc-9');

    expect(messages.error).toHaveBeenCalledWith('ประเมินความเสี่ยงด้วย AI ไม่สำเร็จ');
  });
});
